### PR TITLE
Update fr.po

### PR DESCRIPTION
**Pull request by peutch**
Following @dscho advice from https://github.com/git/git/pull/998#issuecomment-817560868

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @peutch 

A good typo fix.  Please:

1. Write a proper commit message, which should has a subject with prefix "l10n: " and a "s-o-b" trailer like other l10n commits.
2. Please send pull request to @jnavila and to his fork repo: https://github.com/jnavila/git .

**Comment by jnavila** [comment]
Hi, @peutch 

Thank you for your contribution. This patch is already pushed and ready for git next version here:

https://github.com/jnavila/git/commit/0aa006664cc67dc81dfa007682a39e40f9e5dc83

**Comment by peutch** [comment]
Hi, sorry for the noise then. I should have check all those repositories.

**Comment by dscho** [comment]
@peutch I don't think it was noise. It was a good contribution that somebody else happened to contribute slightly earlier than you. Thank you for helping!

**Pull request closed without merging**
