### PR TITLE
l10n: zh_TW.po: v2.31.0 round 2 (15 untranslated)

### PR DESCRIPTION
**Pull request by pan93412**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
Will merge when the draft tag is removed.

**Comment by pan93412** [comment]
> Will merge when the draft tag is removed.

I'm not done for it. How long does the l10n window close from now?

**Comment by jiangxin** [comment]
> > Will merge when the draft tag is removed.
> 
> It was not done. How long does the l10n window close from now?

You can find git calendar here: https://tinyurl.com/gitcal. This l10n update window will be closed on March 15.

**Comment by pan93412** [comment]
There are some strings I don't sure how to translate, so I left it fuzzy.

**Pull request merged**
