### PR TITLE
l10n: bg.po: Updated Bulgarian translation (5652t)

### PR DESCRIPTION
**Pull request by alshopov**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

For a single-commit pull request, please *leave the pull request description
empty*: your commit message itself should describe your changes.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by alshopov** [comment]
Still checking the mismatched patterns - these seem false positives
The 3 obsolete entries are from real messages that I intend to declare for translation

**Comment by jiangxin** [comment]
> Still checking the mismatched patterns - these seem false positives
I will improve the helper to ignore such false positives. Thank you.

**Comment by jiangxin** [comment]
I found some changes in your po file as below:
 
```
-msgid "helper %s does not support 'force'"
+msgid "helper %s does not support '--force'"
 msgstr "насрещната помощна програма „%s“ не поддържа опцията „--force“"
```

Before introducing such changes, there are false positives reported. In order to suppress such false positives, I made some changes in "git-po-helper" to replace arguments like "--force" to "force". See:

```
		/*
		 * In bg translations, add additional "--" characters before command option,
		 * but the original msgid does not have.
		 */
		{
			Pattern: "неправилен параметър към опцията „--update“",
			Replace: "bad value for update parameter",
		},
		{
			Pattern: "включва опцията „--bare“ за голо хранилище",
			Replace: "implies bare",
		},
		{
			Pattern: "„--hard“/„--mixed“/„--soft“",
			Replace: "--{hard,mixed,soft}",
		},
		{
			Pattern: "„%s“ към опцията „--ancestry-path",
			Replace: "ancestry-path argument %s",
		},
		{
			Pattern: "Неправилен режим за „--rebase-merges“: %s",
			Replace: "Unknown rebase-merges mode: %s",
		},
		{
			Pattern: "не поддържа опцията „--force“",
			Replace: "does not support 'force'",
		},
		{
			Pattern: "неправилна стойност за „--mirror“: %s",
			Replace: "unknown mirror argument: %s",
		},
```

But since you have contributed some fixups to upstream like:

```
commit 3a12749b50eb012b2828856fdf864fab67269cfd
Author: Alexander Shopov <ash@kambanaria.org>
Date:   2024-02-16 11:15:34 +0100

    transport-helper.c: trivial fix of error message
    
    Mark --force as option rather than variable names
    
    Signed-off-by: Alexander Shopov <ash@kambanaria.org>
    Signed-off-by: Junio C Hamano <gitster@pobox.com>

diff --git a/transport-helper.c b/transport-helper.c
index e34a8f47cf..7014b9ad70 100644
--- a/transport-helper.c
+++ b/transport-helper.c
@@ -1072,7 +1072,7 @@ static int push_refs_with_export(struct transport *transport,
        set_common_push_options(transport, data->name, flags);
        if (flags & TRANSPORT_PUSH_FORCE) {
                if (set_helper_option(transport, "force", "true") != 0)
-                       warning(_("helper %s does not support 'force'"), data->name);
+                       warning(_("helper %s does not support '--force'"), data->name);
        }
 
        helper = get_helper(transport);
```


, we need to remove the above dirty hack in git-po-helper.

**Comment by jiangxin** [comment]
> , we need to remove the above dirty hack in git-po-helper.

New dirty hacks on bg language in git-po-helper: https://github.com/git-l10n/git-po-helper/commit/b0fff07eb1d5b4ac89b9f8efeda777658afd443d

**Comment by jiangxin** [comment]
We have new translatable messages from upstream v2.45.0-rc1, you can update your translations.

**Pull request merged**
