### PR TITLE
l10n: sv.po: Update Swedish translation (5230t0f0u)

### PR DESCRIPTION
**Pull request by nafmo**
Signed-off-by: Peter Krefting <peter@softwolves.pp.se>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
Typos found using `git-po-helper check-po sv` as follows, and there are many false positives which you can help to contribute to [git-po-helper](https://github.com/git-l10n/git-po-helper).

## s/--chmod-parametern/--chmod parametern/

```
level=warning msg="mismatch variable names: --chmod, --chmod-parametern"
level=warning msg=">> msgid: --chmod param '%s' must be either -x or +x"
level=warning msg=">> msgstr: --chmod-parametern \"%s\" måste antingen vara -x eller +x"
```

## s/--dump-alias/--dump-aliases/
```
level=warning msg="mismatch variable names: --dump-alias, --dump-aliases"
level=warning msg=">> msgid: --dump-aliases incompatible with other options\n"
level=warning msg=">> msgstr: --dump-alias är inkompatibelt med andra flaggor\n"
```
## s/ -unpack-unreachable/ --unpack-unreachable/
```
level=warning msg="mismatch variable names: --unpack-unreachable"
level=warning msg=">> msgid: --keep-unreachable and --unpack-unreachable are incompatible"
level=warning msg=">> msgstr: --keep-unreachable och -unpack-unreachable kan inte användas samtidigt"
```

## s/ -check/ --check/
```
level=warning msg="mismatch variable names: --check"
level=warning msg=">> msgid: --name-only, --name-status, --check and -s are mutually exclusive"
level=warning msg=">> msgstr: --name-only, --name-status, -check och -s är ömsesidigt uteslutande"
```

## s/--separatebgit-dir/--separate-git-dir/
```
level=warning msg="mismatch variable names: --separate-git-dir, --separatebgit-dir"
level=warning msg=">> msgid: --separate-git-dir incompatible with bare repository"
level=warning msg=">> msgstr: --separatebgit-dir är inkompatibelt med naket arkiv"
```

## s/ -source=HEAD/ --source=HEAD
```
level=warning msg="mismatch variable names: --source=HEAD"
level=warning msg=">> msgid: Clone succeeded, but checkout failed.\nYou can inspect what was checked out with 'git status'\nand retry with 'git restore --source=HEAD :/'\n"
level=warning msg=">> msgstr: Klonen lyckades, men utcheckningen misslyckades.\nDu kan inspektera det som checkades ut med \"git status\"\noch försöka med \"git restore -source=HEAD :/\"\n"
```

## s/git-branch-åtgärder/git-branch åtgärder/
```
level=warning msg="mismatch variable names: git-branch"
level=warning msg=">> msgid: Specific git-branch actions:"
level=warning msg=">> msgstr: Specifika git-branch-åtgärder:"
```

## s/dimmed_zebra/dimmed-zebra/
```
level=warning msg="mismatch variable names: dimmed_zebra"
level=warning msg=">> msgid: color moved setting must be one of 'no', 'default', 'blocks', 'zebra', 'dimmed-zebra', 'plain'"
level=warning msg=">> msgstr: färginställningen för flyttade block måste vara en av \"no\", \"default\", \"blocks\", \"zebra\", \"dimmed_zebra\", \"plain\""
```

## s/git fetch-patch/git fetch-pack/
```
level=warning msg="mismatch variable names: git fetch-pack, git fetch-patch"
level=warning msg=">> msgid: git fetch-pack: fetch failed."
level=warning msg=">> msgstr: git fetch-patch: hämtning misslyckades."
```

## s/ -- name/ --name/
```
level=warning msg="mismatch variable names: --name"
level=warning msg=">> msgid: git submodule--helper add-clone [<options>...] --url <url> --path <path> --name <name>"
level=warning msg=">> msgstr: git submodule--helper add-clone [<flaggor>...] --url <url> --path <sökväg> -- name <namn>"
```

## s/--brand/--branch/
```
level=warning msg="mismatch variable names: --branch, --brand"
level=warning msg=">> msgid: git submodule--helper set-branch [-q|--quiet] (-b|--branch) <branch> <path>"
level=warning msg=">> msgstr: git submodule--helper set-branch [-q|--quiet] (-b|--brand) <gren> <sökväg>"
```
## s/[--format=<format]/[--format=<format>]
```
level=warning msg="mismatch variable names: --format="
level=warning msg=">> msgid: git verify-tag [-v | --verbose] [--format=<format>] <tag>..."
level=warning msg=">> msgstr: git verify-tag [-v | --verbose] [--format=<format] <tagg>..."
```

## s/--stdin-commit/--stdin-commits/

```
level=warning msg="mismatch variable names: --stdin-commit, --stdin-commits"
level=warning msg=">> msgid: use at most one of --reachable, --stdin-commits, or --stdin-packs"
level=warning msg=">> msgstr: använd som mest en av --reachable, --stdin-commit och --stdin-packs"
```

## s/--group-flagga/--group flagga/
```
level=warning msg="mismatch variable names: --group, --group-flagga"
level=warning msg=">> msgid: using multiple --group options with stdin is not supported"
level=warning msg=">> msgstr: mer än en --group-flagga stöds inte med standard in"
```

**Comment by jiangxin** [comment]
The l10n window will be closed, I will merge your commit and fix some typos.

**Comment by nafmo** [comment]
I wish there was some feedback when comments are posted to pull requests, but as there are not, this is too late.

> s/--chmod-parametern/--chmod parametern/

This is bad, there is a compound word here, and replacing the hyphen with a space breaks that. The problem is of course that ASCII has the same character for hyphen as for the parameter dash. I will rewrite this to "--chmod"-parametern to make it clear what is the verbatim parameter text.

> s/git-branch-åtgärder/git-branch åtgärder/
> s/--group-flagga/--group flagga/

Same here, these text are now gramatically incorrect. For it to be a noun, it needs to be a single compound word, otherwise it takes the verb part of the sentence, and there is no verb "actions", so that sentence is now non-sensical. The otherone turns into "--group flags" (as in "to flag"), which is also non-sensical.

The other errors caught are good.

**Comment by jiangxin** [comment]
Will update rules for `git-po-helper` to tolerate grammars of some languages. Sorry for this inconvenience.

**Pull request closed without merging**
