### PR TITLE
l10n: Added Russian translation. 100% complete.

### PR DESCRIPTION
**Pull request by DJm00n**
I've completed Russian translation.

### CODE REVIEW

**Comment by jiangxin** [comment]
It's great, welcome to the l10n team.  Would you mind to fixup your commit message a bit?
Because in Git community, the subject (first line) of a commit never ends with a punctuation,
and subject of l10n is always formatted as "l10n: ru: ...", for example.

**Comment by DJm00n** [comment]
@jiangxin, done.

**Comment by jiangxin** [comment]
Hi, @DJm00n  (cc @gitster)

You can send patches for your fixes on i18n to Git mailing list.  Please note
that these fixes are not l10n but i18n things, so add prefix "i18n: " to the 
subject of your commit message, and using git-format-patch and git-am to
send email.

Please note that there are some directions in "po/README" that you should
pay attention to.

1. Do not translate plumbing output, as the "Marking strings for translation"
    section describes.

2. Built git using environment like: GETTEXT_POISON=YesPlease, so that
    you can test whether your update may break things. (See  "Testing marked
    strings" section)

        make GETTEXT_POISON=YesPlease
        cd t && prove -j 9 ./t[0-9]*.sh

3. I remember that @gitster tell me not translate die() message, because it
    may not work properly, but I can not find the message.

**Comment by DJm00n** [comment]
@jiangxin, thank you for answers!

**Pull request merged**
