### PR TITLE
l10n: zh_TW.po: v2.29.0 round 2 (2 untranslated)

### PR DESCRIPTION
**Pull request by pan93412**
Some translations has been left it fuzzy since I don't know how to translate it perfect.

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @pan93412 ,

Cannot find your pgp key to verify your commit?  Find a key but still not valid:

    Search results for 'pan93412 gmail com'
    Type bits/keyID     Date       User ID
    pub  4096R/85E27721 2018-06-21 Yi-Jyun Pan (Yi-Jyun Pan's private key.) <pan93412@gmail.com>
    	 Fingerprint=3DC5 213E AA0F 8267 06BC  3DFA 96BF 8670 85E2 7721

**Comment by jiangxin** [comment]
branch name: "zh_TW/201010", 2010 => 2020?

**Comment by pan93412** [comment]
> Hi @pan93412 ,
> 
> Cannot find your pgp key to verify your commit, forget to publish your pubkey?  Find a key but still not valid:
> 
>     Search results for 'pan93412 gmail com'
>     Type bits/keyID     Date       User ID
>     pub  4096R/85E27721 2018-06-21 Yi-Jyun Pan (Yi-Jyun Pan's private key.) <pan93412@gmail.com>
>     	 Fingerprint=3DC5 213E AA0F 8267 06BC  3DFA 96BF 8670 85E2 7721 

My key is on [Keybase](https://keybase.io/pan93412), and should I re-publish it to a keyserver?

**Comment by pan93412** [comment]
> branch name: "zh_TW/201010", 2010 => 2020?

No. 20[20]-[10]-[10].

**Comment by jiangxin** [comment]
> My key is on [Keybase](https://keybase.io/pan93412), and should I re-publish it to a keyserver?

My gpg can search and download pubkey from hkp://pgp.mit.edu, it's better to upload one there.

**Pull request merged**
