### PR TITLE
i18n: it.po: update the Italian translation for Git 2.27.0 round #2

### PR DESCRIPTION
**Pull request by AlessandroMenti**
This PR updates the Italian translation for Git 2.27.0 round #2.

### CODE REVIEW

**Comment by jiangxin** [comment]
Please the following issues in commit log:

1. Use prefix "l10n:" instead of "i18n:".  i18n means mark message for translation.
2. The subject line of the commit log is too long, less than 50 character is better.

**Comment by AlessandroMenti** [comment]
@jiangxin Done!

**Comment by jiangxin** [comment]
Hi @AlessandroMenti ,  where can I get your pubkey to validate your commit?
Cannot find key  `BAF20A23583C849B034DD484467AC0B4D6A6F336` in `pgp.mit.edu`.

    $ LC_ALL=C git log -1 --show-signature \
        a09c79f5c85caadcbd1e7688e3c9226209acbbe0
    commit a09c79f5c85caadcbd1e7688e3c9226209acbbe0 (l10n/it/AlessandroMenti/update-italian-translation)
    gpg: Signature made Thu May 28 13:54:18 2020 CST
    gpg:                using RSA key BAF20A23583C849B034DD484467AC0B4D6A6F336
    gpg:                issuer "alessandro.menti@alessandromenti.it"
    gpg: Can't check signature: No public key
    Author: Alessandro Menti <alessandro.menti@alessandromenti.it>
    Date:   Wed May 27 18:22:22 2020 +0200
    
        l10n: it.po: update for Git 2.27.0 round #2
        
        Signed-off-by: Alessandro Menti <alessandro.menti@alessandromenti.it>

**Comment by AlessandroMenti** [comment]
I am using a separate Git subkey to sign my commits, hence why you can't find it by its ID on public keyservers - you will have to retrieve my main key, which is `0xBF334213F5C5CA03` (fingerprint: `6731 DDC2 8357 BEC3 8E34  2AAF BF33 4213 F5C5 CA03`) and is available on `pgp.mit.edu` (as well as on [my Web site](https://www.alessandromenti.it/downloads/pubkey-0xBF334213F5C5CA03.asc)).

**Pull request merged**
