### PR TITLE
Add Turkish translations

### PR DESCRIPTION
**Pull request by bitigchi**
Hello,

This PR adds Turkish translations for Git. Translations are complete, but I am still testing them in runtime, so I wanted to open this PR in the meantime for any possible checks from your side.

I'll be done with testing in a day or two.

### CODE REVIEW

**Comment by bitigchi** [comment]
Question: Is the last `%s` is a line number or some content from the line in `msgid "(body) Adding cc: %s from line '%s'\n"`?

**Comment by jiangxin** [comment]
> Question: Is the last `%s` is a line number or some content from the line in `msgid "(body) Adding cc: %s from line '%s'\n"`?

It's not a line number, but the whole line which has a matched pattern.

**Comment by bitigchi** [comment]
Below line does not seem to be displaying, I'm getting English text:
```
#: git-rebase--preserve-merges.sh:755
#, sh-format
msgid "Successfully rebased and updated $head_name."
msgstr "$head_name başarıyla yeniden temellendirildi ve güncellendi."
```

@jiangxin, have you ever experienced this issue?

**Comment by bitigchi** [comment]
I've been testing for the last few days, and I can say it's ready from my side. Thanks.

**Comment by jiangxin** [comment]
There are to many trivial commits, please squash them into one commit.
You can do this using an interactive rebase, and not forget write a proper log message.
If you don't know how to do this, I can help.

**Pull request closed without merging**
