### PR TITLE
l10n: vi: Updated translation for 2.45

### PR DESCRIPTION
**Pull request by Nekosha**

### CODE REVIEW

**Comment by jiangxin** [comment]
Use proper email address for the author and committer field in your commit, do not use such email address as below:

```
commit 5a1a9c6b8883c6b30d26d9b14f446ffd842ed828
Author:     Nekosha <79341606+Nekosha@users.noreply.github.com>
AuthorDate: 2024-04-16 15:30:26 +0700
Commit:     Nekosha <79341606+Nekosha@users.noreply.github.com>
CommitDate: 2024-04-18 16:49:52 +0700

    l10n: vi: Updated translation for 2.45 (round 1)
    
    Signed-off-by: Vũ Tiến Hưng <newcomerminecraft@gmail.com>
```

**Comment by Nekosha** [comment]
This is still a work in progress, I will squash this on Apr 28th.

**Comment by jiangxin** [comment]
Before it is ready for merge, not forget to turn off the draft mode, and you can choose to squash your commits.

**Comment by Nekosha** [comment]
Translations have been completed and commits have been squashed. Please pull translation for Git 2.45. Thanks.

**Pull request merged**
