### PR TITLE
Start on nb translation.  Add myself as "team leader".

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Completed the output for 'git status'.  It will take a while to get
through the entire set.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Btw, did you consider using a web based translation framework, like https://hosted.weblate.org/ ?

**Comment by jiangxin** [comment]
Hi @petterreinholdtsen,

Thank you for your contribution, but git l10n only receives contributions on po/, not includes git-gui/*.
Changes on 'git-gui/*' should send to git-gui maintainer Pat Thoyts, according to `Documentation/SubmittingPatches`.

**Comment by jiangxin** [comment]
And do not add a period in the subject of your commit message.  See `Documentation/SubmittingPatches`:

    The first line of the commit message should be a short description (50
    characters is the soft limit, see DISCUSSION in linkgit:git-commit[1]),
    and should skip the full stop.  It is also conventional in most cases to
    prefix the first line with "area: " where the area is a filename or
    identifier for the general area of the code being modified, e.g.
    
        * doc: clarify distinction between sign-off and pgp-signing
        * githooks.txt: improve the intro section

**Comment by jiangxin** [comment]
Other issues:

1. You should also add a s-o-b line in your commit message.
2. Add a prefix "l10n: " in the subject of your commit.  See how other contributers write commit log.

**Comment by petterreinholdtsen** [comment]
Thank you for the review.  I've tried to address all your findings.

But I must admit requiring translators to send translators several places, seem like a sure way to make life harder for translators.

**Comment by jiangxin** [comment]
I will create a WIP (work in progress) branch for you, and will merge it back to master when you finish most of the translations.

BTW, you should rename your branch name from `git-i18n-nb` to `git-l10n-nb`. i18n and l10n are quite different, i18n includes marking strings for translation, and l10n includes translating.

**Comment by petterreinholdtsen** [comment]
[Jiang Xin]
> I will create a WIP (work in progress) branch for you, and will merge
> it back to master when you finish most of the translations.

My priority is to get the most shown messages translated, to provide my
son with more understandable messages when using git, not most of the
translation, which is a lot of messages rarely shown.  If the
translation I have capasity to complete are not going to show up in the
official git repository until most of the translations are done, it seem
pointless for me to spend time on the translation.  Is there a better
way to do it?

> BTW, you should rename your branch name from `git-i18n-nb` to
> `git-l10n-nb`. i18n and l10n are quite different, i18n includes
> marking strings for translation, and l10n includes translating.

Good point, I'll do it.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by jiangxin** [comment]
> My priority is to get the most shown messages translated, to provide my son with more understandable messages when using git, not most of the translation, which is a lot of messages rarely shown. If the translation I have capasity to complete are not going to show up in the official git repository until most of the translations are done, it seem pointless for me to spend time on the translation. Is there a better way to do it?

It's reasonable, but 13 translated messages are too small in my opinion. We should define a mimal set of messages for new l10n team to complete. 

* Choose the frequently used git commands.
* Extract l10n messages from them as the mimal l10n set.

**Comment by petterreinholdtsen** [comment]
[Jiang Xin]
> It's reasonable, but 13 translated messages are too small in my
> opinion. We should define a mimal set of messages for new l10n team to
> complete.

Well, I decided to send my translations early, to get a better
understanding of the submission process.  I saw no reason to spend a lot
of time on the translation, only to discover the process made it
impossible to get the translations included, so I wanted to get feedback
early. :)

While I agree that such minimal set would be very useful, it currently
sound like some moving target it is impossible to know when is reached,
which is affecting the motivation to continue.  It would be very useful
to know now what is required to get the translation accepted.

I hope you can clarify this in the new pull request, as this one was
closed when I renamed the branch.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request closed without merging**
