### PR TITLE
l10n: ru.po: Update Russian translation

### PR DESCRIPTION
**Pull request by DJm00n**

### CODE REVIEW

**Comment by jiangxin** [comment]
```
too many obsolete entries (165) in comments, please remove them 
```

The obsolete entries are comment entries at the end of your po file. E.g.:

```
#~ msgid "..."
#~ msgstr "..."

#~ msgid "..."
#~ msgstr "..."
```

You can remove them to make po file smaller.

**Comment by DJm00n** [comment]
Squashing those commits seems to have helped.

**Comment by jiangxin** [comment]
Will merge after rc2 is released.

**Comment by jiangxin** [comment]
Hi, @DJm00n 

A new translatable string was found in git 2.37.0-rc2, please update your translation and refresh this pull request.

**Comment by jiangxin** [comment]
Hi @DJm00n , I will make an amend commit to update your `po/ru.po`, and merge your commit.

**Comment by DJm00n** [comment]
@jiangxin thank you!

**Pull request closed without merging**
