### PR TITLE
Language translation: Spanish (es).

### PR DESCRIPTION
**Pull request by nelson6e65**
I would like to be Spanish (:es:) translator for Git.

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi Nelson, Welcome to the git l10n team.  Git 2.10 will be released next month,
I wish your contribution can be merged in time.

There are some issues:

1. There are no proper prefix and no signed-off-by line in your commit log, you can learn how to write commit log from other l10n contributors, see:

        $ git log --no-merges -- po

2. No translations at all in `po/es.po`. I will create a work-in-progress branch as `WIP/es/nelson` before you complete most of them.

**Comment by nelson6e65** [comment]
:smiley:

>There are no proper prefix and no signed-off-by line in your commit log, you can learn how to write commit log from other l10n contributors

Thanks! I'll check to follow standard. :thumbsup:

> No translations at all in po/es.po. I will create a work-in-progress branch as WIP/es/nelson before you complete most of them.

Yes. I was waiting a response in order to start to translate.

I'll start later this night. :relaxed:

**Comment by nelson6e65** [comment]
@jiangxin Should I commit & push progress...? Each 20% completion or something?

**Comment by jiangxin** [comment]
How about the progress?  Git 2.11.0 will be released next Wednesday.

**Comment by nelson6e65** [comment]
Hi. Sorry for delay.

Well... Is 18% done, but not updated [since 2 months ago](https://www.transifex.com/nelson6e65/git-po). 😔 I had been very busy in other projects in my work.

I'll try update my sources and translate al least to 25% for this weekend. Not will be ready for 2.11.0, if I make 10% each week, it may be ready before 2.12.0 release.

I'm meticulous, and some technical expressions are not easy to translate, so I read some in Pro Git Book translations and specially the [Git glosary](https://git-scm.com/docs/gitglossary) to use an accurate/convention translation.

**Comment by DJm00n** [comment]
Hi, @nelson6e65 !
I can advice you to cooperate with ProGit2 book translation team: https://github.com/progit/progit2-es
I think folks there can help you with complex terms. Good luck.

**Pull request closed without merging**
