### PR TITLE
l10n: zh_TW.po: v2.30.0 round 2 (1 untranslated)

### PR DESCRIPTION
**Pull request by pan93412**
Signed-off-by: pan93412 <pan93412@gmail.com>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

```
$ msgfmt -o /dev/null --stat po/zh_TW.po 
已翻譯 5036 條訊息，未翻譯 1 條訊息.
```

### CODE REVIEW

**Comment by pan93412** [comment]
[git-zhtw-8d0c422.diff.zip](https://github.com/git-l10n/git-po/files/5735717/git-zhtw-8d0c422.diff.zip)

The difference of the bare translation changes.

**Comment by jiangxin** [comment]
> [git-zhtw-8d0c422.diff.zip](https://github.com/git-l10n/git-po/files/5735717/git-zhtw-8d0c422.diff.zip)
> 
> The difference of the bare translation changes.

Here is a diff driver for changes of a l10n update:

+ https://github.com/git-l10n/git-po/blob/po-helper/diff-driver/gitconfig
+ https://github.com/git-l10n/git-po/blob/po-helper/diff-driver/attributes

**Comment by jiangxin** [comment]
In `po/TEAMS` file, the authoritative repository is `https://github.com/l10n-tw/git-po`. But this time you send from another one?

**Comment by pan93412** [comment]
> In `po/TEAMS` file, the authoritative repository is `https://github.com/l10n-tw/git-po`. But this time you send from another one?

It seemed like that GitHub set a new name for my new-forked repository. I've renamed it to the correct one.

**Comment by jiangxin** [comment]
When building git on some old release of Linux, may have an old version of `gettext`.  Therefore, I will check the backward compatibility of `gettext`.

Errors found in `po/zh_TW.po` when checking using gettet 0.14.4:

    $ /opt/gettext/0.14.4/bin/msgfmt  --check --statistics  po/zh_TW.po
    po/zh_TW.po:25273:4: parse error
    po/zh_TW.po:25273: missing `msgstr' section
    po/zh_TW.po:25307:4: parse error
    po/zh_TW.po:25307: missing `msgstr' section
    /opt/gettext/0.14.4/bin/msgfmt: found 4 fatal errors

**Comment by pan93412** [comment]
@jiangxin fixed. could you take a look? :)

**Comment by Denton-L** [comment]
Hi @pan93412, just a quick note: you should configure your `user.name` variable to your real name so that commits and sign-offs are done with your real name which is [required by the project](https://github.com/git-l10n/git-po/blob/v2.29.0/Documentation/SubmittingPatches#L356).

**Comment by pan93412** [comment]
> Hi @pan93412, just a quick note: you should configure your `user.name` variable to your real name for the future so that commits and sign-offs are done with your real name which is [required by the project](https://github.com/git-l10n/git-po/blob/v2.29.0/Documentation/SubmittingPatches#L356).

Thanks for notifying!

**Pull request merged**
