### PR TITLE
l10n: pl.po: add Polish translation

### PR DESCRIPTION
**Pull request by Arusekk**
This is based upon kind of outdated .pot and work started by @mkljczk.

I did not know whether to start upon the old thing or a fresher one, and I am not quite sure whether older versions' strings are still present in newer .pot file, so I did what was the easiest at the time.

Please give me a hand using msgmerge or whatever the tool is if this needs to be updated, and guide me a little through the updating process, since I am not a very experienced translator.

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi, @Arusekk 

There is a l10n helper program for git at: https://github.com/git-l10n/git-po/blob/po-helper/utils/po-helper.sh.  It is just a wrapper on gettext utilities.  You can use it or use gettext utilities.

1. I find your translations are based on git 2.11.0:

        $ git describe
        v2.11.0-198-g2ddc69e6ec

2. Junio released git v2.30.0-rc0 yesterday, and we are in the new l10n update window. You should rebase your commit on it by using the following commands for example:

        $ git fetch git@github.com:git-l10n/git-po.git master
        $ git rebase FETCH_HEAD

3. Update your `po/pl.po` by running:

        $ po-helper.sh update pl.po

   or using:

        $ msgmerge --add-location --backup=off -U po/pl.po po/git.pot

4. After this update, you can inspect `pl.po` file by running:

        $ po-helper.sh check pl.po
        pl.po : 2572 translated messages, 1399 fuzzy translations, 1067 untranslated messages.
            [gettext 0.14] ok
            [core pl] ................................................ done.
            [core pl] 370 translated messages, 71 fuzzy translations, 37 untranslated messages.

5. Open `pl.po` with your favorite editor. I use emacs with po-mode for translating.

        $ emacs po/pl.po

6. See our pull request archives for conventions of git l10n:

    + https://github.com/git-l10n/git-po/pulls?q=is%3Apr+is%3Aclosed+label%3Astyle%21

7. Take the leader by providing an entry for your language in `po/TEAMS` file in a standalone commit. See pull request archives on this topic:

    + https://github.com/git-l10n/git-po/pulls?q=label%3Anew-team+is%3Aclosed

**Comment by jiangxin** [comment]
Hi, @Arusekk 

Please add a "Signed-off-by:" signature to your commits,  like others.  You can find more conventions from our pull request archives:

+ https://github.com/git-l10n/git-po/pulls?q=is%3Apr+is%3Aclosed+label%3Astyle%21

**Comment by Arusekk** [comment]
I guess I will probably not make it in this l10n window, as I translate it part-time by myself. Thanks a lot for the help, anyway, I think I can handle it now. I will squash and sign my commits off in the end, and I now work on a different branch (pl-next) to reduce noise sent to those subscribed to this PR. Also marking it as draft so that it looks less ready.

**Comment by jiangxin** [comment]
Pulled, thank you.

**Pull request merged**
