### PR TITLE
Fix typos in French translation

### PR DESCRIPTION
**Pull request by ewjoachim**

### CODE REVIEW

**Comment by jnavila** [comment]
In fact, this PR cannot be accepted in the present form:

 * the subject must be prefixed by "l10n: fr.po"
 * the commit must present a "Signed-off-by:" line (commit with option "-s")

For further information, please read the files https://github.com/git-l10n/git-po/blob/master/Documentation/SubmittingPatches and https://github.com/git-l10n/git-po/blob/master/po/README

**Comment by ewjoachim** [comment]
Done. Thank you for your patience, it's my first contribution to git / git-l10n.

**Comment by jiangxin** [comment]
Hi @ewjoachim,

Thank your for your contribution.  I think this PR should be created in [jnavila/git](https://github.com/jnavila/git) forked by @jnavila, and can add additional signed-off-by line from @jnavila.  Please close this after creating a new one in the right place.

**Comment by jnavila** [comment]
@ewjoachim Do not bother to change the PR. I'm picking it up as is, just adding a Rewiewed-by line.

**Comment by jnavila** [comment]
you can find the ongoing fr_l10n_next here:

https://github.com/jnavila/git/tree/fr_l10n_next

**Comment by ewjoachim** [comment]
Yep, I can see it in jnavila@53f7206d0f1b827d

Perfect, thank you !

**Pull request closed without merging**
