### PR TITLE
l10n: bg.po: Updated Bulgarian translation (5211t)

### PR DESCRIPTION
**Pull request by alshopov**
Signed-off-by: Alexander Shopov <ash@kambanaria.org>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by alshopov** [comment]
Thank you very much for the patience and the continuous stream of improvements on git-po-helper
After running the updated version I get just 2 warnings:

---------

```
mismatch variable names: %%(trailers:key=<...>), %%(trailers:key=СТОЙНОСТ) 
msgid: expected %%(trailers:key=<value>) 
msgstr: очаква се %%(trailers:key=СТОЙНОСТ) 
```

As you advised me previously - `key` is now left untranslated. I believe there is a mismatch between <value> and СТОЙНОСТ but this should be fine

---------
```
mismatch variable names: git merge-base 
msgid: use 'merge-base --fork-point' to refine upstream 
msgstr: git merge-base --fork-point
```
There is a mismatch between `merge-base --fork-point` and `git merge-base --fork-point`. Would you agree the best solution would be to fix the original message?

**Comment by alshopov** [comment]
TBH - I am a bit undecided whether 
`trailers:key=<value>)`
should be 
`%%(trailers:key=СТОЙНОСТ)` - _СТОЙНОСТ_ means **value**
or 
`%%(trailers:key=КЛЮЧ)` - _КЛЮЧ_ means **key**

**Comment by jiangxin** [comment]
> TBH - I am a bit undecided whether `trailers:key=<value>)` should be `%%(trailers:key=СТОЙНОСТ)` - _СТОЙНОСТ_ means **value** or `%%(trailers:key=КЛЮЧ)` - _КЛЮЧ_ means **key**

`<value>` is the value of the key. You can try the following commands:

Show s-o-b trailer for each commit:

```
git log --pretty="%(trailers:key=Signed-off-by)"
```

Show reported-by trailer for each commit:

```
git log --pretty="%(trailers:key=reported-by)"
```

**Comment by jiangxin** [comment]
> Thank you very much for the patience and the continuous stream of improvements on git-po-helper After running the updated version I get just 2 warnings:
> 
> ```
> mismatch variable names: %%(trailers:key=<...>), %%(trailers:key=СТОЙНОСТ) 
> msgid: expected %%(trailers:key=<value>) 
> msgstr: очаква се %%(trailers:key=СТОЙНОСТ) 
> ```
> 
> As you advised me previously - `key` is now left untranslated. I believe there is a mismatch between and СТОЙНОСТ but this should be fine
> 
> ```
> mismatch variable names: git merge-base 
> msgid: use 'merge-base --fork-point' to refine upstream 
> msgstr: git merge-base --fork-point
> ```
> 
> There is a mismatch between `merge-base --fork-point` and `git merge-base --fork-point`. Would you agree the best solution would be to fix the original message?

I can update smudge map for bg to suppress warnings for these cases.

**Comment by alshopov** [comment]
> trailer
Thanx a lot for the explanation. It seems I already have a term for that that I will use: _епилог_ .
> update smudge map
I see you already did. Thanx. I see you also keep reasons in the file, so perhaps we can propose patches upstream

Now let me comment on:
> Not keep symbols "<" and ">", the reason is?
Two main reasons:
- safety
- brevity

Safety: people copy and paste. The <> symbols can be especially dangerous when forgotten in a command interpreted by a shell.
Brevity: Bulgarian is written in Cyrillic rather than Latin. Thus it is most frequently obvious where a word comes from - a word with Cyrillic letters is obviously coming from the translation. Capitalization rules are somewhat similar to rest of European languages. So a word in UPPERCASE is obviously a special term - so I use UPPERCASED_EXPRESSION to denote where a substitution shoould be made, and in the translation I can even change all UPPERCASED_EXPRESSIONs a bit - showing the literal part they point to while keeping the text in proper Bulgarian as words change.

I really like the result - it is safer, shorter and natural.

I will change the push request shortly to fix the key issue.

**Comment by alshopov** [comment]
Corresponding fix here: https://github.com/git-l10n/git-po-helper/pull/8

**Comment by jiangxin** [comment]
> Corresponding fix here: [git-l10n/git-po-helper#8](https://github.com/git-l10n/git-po-helper/pull/8)

Will merge, thanks.

**Pull request merged**
