### PR TITLE
l10n: ko.po: Beginning Korean message translation

### PR DESCRIPTION
**Pull request by changwoo**
Signed-off-by: Changwoo Ryu <cwryu@debian.org>

I'd like to start a new translation team. There seems to be no other Korean translation effort.

It's just a beginning so the actual translation is almost empty.

### CODE REVIEW

**Comment by jiangxin** [comment]
Only changes on files under “po/” directory are allowed.  You should send
patches on "git-gui/po/ko.po" to Pat Thoyts, see: Documentation/SubmittingPatches

    commit 7529d8a4c7b14d667ba195710159e69614147d83
    Author: Changwoo Ryu <cwryu@debian.org>
    Date:   Wed Dec 9 20:16:56 2015 +0900

        l10n: ko.po: Beginning Korean message translation
    
        Signed-off-by: Changwoo Ryu <cwryu@debian.org>

     git-gui/po/ko.po |  2401 ++++++++++++
     po/TEAMS         |     4 +
     po/ko.po         | 11202 +++++++++++++++++++++++++++++++++++++++++++++++++++++
     3 files changed, 13607 insertions(+)

**Comment by jiangxin** [comment]
The subject of this commit does not has the prefix "l10n: ko: ",
and please send a complete translation in one commit.

    commit 17134c137a0effbc8ef1998e49ccc762ea872b2e
    Author: Hyunjun Kim <yoloseem@users.noreply.github.com>
    Date:   Wed Dec 9 22:54:10 2015 +0900

        Translate [new $term] strings to ko

     po/ko.po | 6 +++---
     1 file changed, 3 insertions(+), 3 deletions(-)

**Comment by changwoo** [comment]
Thanks. Fixed according to your review.

**Comment by changwoo** [comment]
Updated & rebased for v2.7.0 round 1 pot

**Comment by jiangxin** [comment]
First, there are some issues in your translations:

    po/ko.po:642: 'msgid' and 'msgstr[0]' entries do not both begin with '\n'
    po/ko.po:1187: 'msgid' and 'msgstr' entries do not both end with '\n'
    msgfmt: found 2 fatal errors

and, I found you have finished only 10% of translation, so I will hold your 
contribution in a WIP(work-in-progress) branch.

    ko.po: 318 translated messages, 2159 untranslated messages.

**Comment by changwoo** [comment]
Fixed msgcheck errors. 

But there doesn't seem to be enough time to keep the translations up-to-date for v2.7.0. For now you can just put it in the WIP branch and close this PR.

**Comment by jiangxin** [comment]
OK, send a new PR, when you complete the translation.

**Pull request closed without merging**
