### PR TITLE
po/it.po: Remove space between the dashes and start of an option's name in the Italian translation

### PR DESCRIPTION
**Pull request by carzacc**
Signed-off-by: Carmine Zaccagnino <carmine@carminezacc.com>

As I was asked in response to https://github.com/git/git/pull/555#event-2431000862

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @carzacc ,

There is a team for l10n of Italian, and the leader is Alessandro Menti.  Please read [po/TEAMS](https://github.com/git/git/blob/master/po/TEAMS) and [po/README](https://github.com/git/git/blob/master/po/README) for how to contribute.

Thanks

**Comment by AlessandroMenti** [comment]
Hi @carzacc,
thanks for the PR - since the issue is still there (I've finished translating all missing messages only a few days ago, and I still need to review the existing strings, so this bug has gone unnoticed so far), would you like me to commit it in your name?

**Comment by carzacc** [comment]
That's great, go ahead and do it!
________________________________
Da: Alessandro Menti <notifications@github.com>
Inviato: giovedì 27 giugno 2019 20:38
A: git-l10n/git-po
Cc: Carmine Zaccagnino; Mention
Oggetto: Re: [git-l10n/git-po] po/it.po: Remove space between the dashes and start of an option's name in the Italian translation (#377)


Hi @carzacc<https://github.com/carzacc>,
thanks for the PR - since the issue is still there (I've finished translating all missing messages only a few days ago, and I still need to review the existing strings, so this bug has gone unnoticed so far), would you like me to commit it in your name?

**Comment by AlessandroMenti** [comment]
Done, see #381.

**Pull request closed without merging**
