### PR TITLE
l10n: zh_TW.po: v2.28.0 round 1 (2 untranslated)

### PR DESCRIPTION
**Pull request by pan93412**
Signed-off-by: Yi-Jyun Pan <pan93412@gmail.com>

I'm not really sure what is the meaning of the remaining 2 strings, so I just leave them fuzzy.

### CODE REVIEW

**Comment by jiangxin** [comment]
You can see `ANONYMIZING` section of manpage of `git fast-export` for l10n of this message:

    #: builtin/fast-export.c:1227
    msgid "convert <from> to <to> in anonymized output"
    msgstr "在匿名输出中将 <from> 转换为 <to>"

And the following l10n message will appear in `git status --long` for a sparse-checkout repostory:

    #: wt-status.c:1494
    #, c-format
    msgid "You are in a sparse checkout with %d%% of tracked files present."
    msgstr "您处于稀疏签出状态，包含 %d%% 的跟踪文件"

**Comment by pan93412** [comment]
> You can see `ANONYMIZING` section of manpage of `git fast-export` for l10n of this message:
> 
> ```
> #: builtin/fast-export.c:1227
> msgid "convert <from> to <to> in anonymized output"
> msgstr "在匿名输出中将 <from> 转换为 <to>"
> ```
> 
> And the following l10n message will appear in `git status --long` for a sparse-checkout repostory:
> 
> ```
> #: wt-status.c:1494
> #, c-format
> msgid "You are in a sparse checkout with %d%% of tracked files present."
> msgstr "您处于稀疏签出状态，包含 %d%% 的跟踪文件"
> ```

Thanks! I'll translate those in round 2.

**Comment by jiangxin** [comment]
> > You can see `ANONYMIZING` section of manpage of `git fast-export` for l10n of this message:
> > ```
> > #: builtin/fast-export.c:1227
> > msgid "convert <from> to <to> in anonymized output"
> > msgstr "在匿名输出中将 <from> 转换为 <to>"
> > ```
> > 
> > 
> > And the following l10n message will appear in `git status --long` for a sparse-checkout repostory:
> > ```
> > #: wt-status.c:1494
> > #, c-format
> > msgid "You are in a sparse checkout with %d%% of tracked files present."
> > msgstr "您处于稀疏签出状态，包含 %d%% 的跟踪文件"
> > ```
> 
> Thanks! I'll translate those in round 2.

There may be no round 2, if no l10n related updates in upstream.  So if you want to update, do it now.

**Comment by pan93412** [comment]
Could you review this? @jiangxin

**Comment by jiangxin** [comment]
will merge.

**Pull request merged**
