### PR TITLE
l10n: zh_TW: v2.37.0 round 1

### PR DESCRIPTION
**Pull request by pan93412**
- l10n: zh_TW: remove locations in file
- l10n: zh_TW: v2.37.0 round 1

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @pan93412 , please fix the above errors from CI pipeline.

**Comment by pan93412** [comment]
> Hi @pan93412 , please fix the above errors from CI pipeline.

I will squash them after working on other changes. Thanks!

**Comment by jiangxin** [comment]
> r? @jiangxin

r stands for what?  This PR is ready for merge?

**Comment by pan93412** [comment]
> > r? @jiangxin
> 
> r stands for what?  This PR is ready for merge?

`r?` means “review?”, whose variants are “How about this?”, “cc”. Really sorry about the lacking of the explanation of this usage and the impolite. 😣

**Pull request merged**
