### PR TITLE
Make the French translation gender neutral

### PR DESCRIPTION
**Pull request by ewjoachim**
Based on #208 , just adds gender neutral adjectives (there's no need to assume a software developer needs to be a male).

We could also do it by changing the whole sentence
e.g.:
>  quand vous êtes satisfait de vos modifications

would become
> quand vos modification vous donnent satisfaction

> Si vous êtes sûr que vous voulez la supprimer

Could be phrased as
> Si vous souhaitez réellement la supprimer

> Après vous être assuré que toute modification précieuse a été sauvegardée

would be
> Après avoir vérifié que toute modification précieuse a été sauvegardée

> Êtes-vous sûr ?

would be
> Valider/Confirmer ce choix ?

(I can make it independent of #208, it's just that both are touching the same line, so I'm trying to avoid a conflict)

### CODE REVIEW

**Comment by jnavila** [comment]
I reject this change. The actual form is already gender neutral, as per french grammatical rules, so there is no need to add this gibberish that doesn't make sense for the average french reader.

**Comment by jnavila** [comment]
Unfortunately, this change is a mix of perfectly acceptable typo fixes and of the "gender neutral" thingy.

**Comment by ewjoachim** [comment]
Yes, as I said in the PR description, this PR is based on #208 so as long as #208 is not merged, this PR will show both sets of changes. And as I said, I can rebase it to be independant, it's just that when #208 is accepted (and I guess it will be accepted before this one...), it will make a conflict.

You can see the specific commit that this PR adds in the "commits" section.

I'm ok if you don't want to add "gibberish" (no need to be condescending), I suggested another way in the PR description. Would you be OK with this ? I changed the PR to reflect this.

This software is used by many different people and the changes suggested above are a small step towards better inclusivity with a quite limited (if existant) cost. It may not affect you the way it affects others.

**Comment by jnavila** [comment]
No problem with these changes.

**Comment by ewjoachim** [comment]
Thank you very much :)

For the record, it's been added in jnavila/git@d472d43c87a12bccfb

**Pull request closed without merging**
