### PR TITLE
l10n: sv.po: Update Swedish translation

### PR DESCRIPTION
**Pull request by nafmo**

### CODE REVIEW

**Comment by jiangxin** [comment]
> WARNING [po/sv.po@974ee4a]	mismatched patterns: --ancestry-path, --ancestry-path-argumentet 
> WARNING [po/sv.po@974ee4a]	>> msgid: could not get commit for --ancestry-path argument %s 
> WARNING [po/sv.po@974ee4a]	>> msgstr: kunde inte hämta incheckning för --ancestry-path-argumentet %s 

Is it easy for Swedes to distinguish that the real argument is not "--ancestry-path-argumentet" but "--ancestry-path"?

> ERROR commit 974ee4a: line #3 ("Also fixes ...") is too long: 77 > 72 
> INFO checking commits: 0 passed, 1 failed.        

You can add Anders Jonsson's signature in trailer just before your signature like:

    Reported-by: Anders Jonsson <anders.jonsson@norsjovallen.se>.
    Signed-off-by: Peter Krefting <peter@softwolves.pp.se>

Add write a shorter description for that.

**Comment by nafmo** [comment]
Thanks. I'll fix it by quoting the argument, like I did for the "--buffer mode" message. I will also fix the message. I just haven't got around to doing it yet.

**Comment by nafmo** [comment]
I found a couple of more cases where I had had to hyphenate, "--stdin mode" and also things like ".gitmodules entry", ".git file", "gitdir file" and similar. I changed those to add quotes around the option or filename part.

**Comment by jiangxin** [comment]
We have new translatable messages from upstream v2.45.0-rc1 and you can update your translations.

**Pull request merged**
