### PR TITLE
l10n: pt_PT: update portugal's portuguese lead

### PR DESCRIPTION
**Pull request by alexandre1985**
Update Portuguese Lead and official Repository.
`make` done at the top-level of this repository. Without any error.

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @alexandre1985 ,

Your pull request broke convention no.1 and no.3, please fix them.

Conventions for l10n commit:
1. Add a "l10n: " prefix in the subject of your commit log. See examples: git log --no-merges -- po/
2. The subject (the first line) of your commit log should not exceed 50 characters, and the other lines of your commit log should not exceed 72 characters.
3. Add a "Signed-off-by" line in the trailer of your commit log like other commits of Git.
4. No syntax errors in your translation.
5. Squash trivial commits to make history clear.
6. Do not change files outside the `po` directory.
7. Subprojects "git-gui" and "gitk" have their own workflow, DO NOT send pull request for these project here. See `Documentation/SubmittingPatches`.

See comments of other pull requests with style issues: https://github.com/git-l10n/git-po/pulls?q=is%3Apr+label%3Astyle%21+is%3Aclosed

**Comment by jiangxin** [comment]
The new repository for pt_PT l10n team is `https://github.com/git-l10n-pt-PT/git-po`, not `https://github.com/git-l10n-pt-PT`.  @alexandre1985

**Comment by alexandre1985** [comment]
it is done.
do I need to create a new github pull request now?
there is no button to re-submit this opened pull request.

**Comment by jiangxin** [comment]
You'd better split changes on `po/TEAMS` to a separate commit:  one commit has prefix "l10n: pt_PT: " with changes of `po/pt_PT.po` and another commit has prefix "l10n: " with changes on `po/TEAMS`.

**Pull request merged**
