### PR TITLE
l10n: es: v2.38.0 round 2

### PR DESCRIPTION
**Pull request by ChrisADR**
Signed-off-by: Christopher Diaz Riveros <christopher.diaz.riv@gmail.com>

I've tried to generate the location-less file, but maybe I'm not following the README correctly, or something else is missing, but I'll try to fix it for the next iteration, sorry for the delay.

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
As you said in your description, you failed to generate a locationless po file, that's why your commit is bigger than the others:

Out of command `git log --no-merges --oneline --stat github/main..`

```
653ca3d5b3 l10n: es: v2.38.0 round 2
 po/es.po | 8191 ++++++++++++++++++++++++++++++++++++++++++++++++++++++--------
 1 file changed, 7131 insertions(+), 1060 deletions(-)
d1e76d5ddc l10n: fr: don't say that merge is "the default strategy"
 po/fr.po | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
d5be499eed l10n: zh_CN v2.38.0 rounds 1 & 2
 po/zh_CN.po | 1541 ++++++++++++++++++++++++++++++++++++++++-------------------
 1 file changed, 1057 insertions(+), 484 deletions(-)
d4df8609f3 l10n: po-id for 2.38 (round 2)
 po/id.po | 543 ++++++++++++++++++++++++++++++++-------------------------------
 1 file changed, 275 insertions(+), 268 deletions(-)
20f5a4f114 l10n: tr: v2.38.0 round 2
 po/tr.po | 410 +++++++++++++++++++++++++++++++++------------------------------
 1 file changed, 217 insertions(+), 193 deletions(-)
```

You can use the following commands to make a location-less file:

```
msgcat --no-location po/es.po >po/es.po.new
mv po/es.po.new po/es.po
git add po/es.po
git commit --amend
```

**Comment by jiangxin** [comment]
Find another update in upsteam, see: 

 - https://github.com/git-l10n/pot-changes/blob/pot/main/2022-09-23.diff

Please rebase your commit to the master branch, and translate the new message.

**Comment by alexhenrie** [comment]
For the record, the translations that Chris is submitting appear to be machine translations: There are lots and lots of mistakes. But aside from that, the Spanish translation really needs a glossary like the French and Catalan translations so that important technical words are always translated in the same way. I would be happy to help with this if Chris is willing.

**Comment by alexhenrie** [comment]
I could also work on fixing up Chris's translations, but I had already done a complete translation for version 2.38 thinking that Chris was not going to do one. In my opinion, for this release it would be better to leave the machine translations behind and just take the ones that I did myself: https://github.com/alexhenrie/git-po/commits/es

**Comment by alexhenrie** [comment]
To be clear, I will do the job of fixing the machine translations if need be, but looking through the commit I'm guessing that I would have to modify about half of the messages to make them intelligible.

**Comment by jiangxin** [comment]
> I could also work on fixing up Chris's translations, but I had already done a complete translation for version 2.38 thinking that Chris was not going to do one. In my opinion, for this release it would be better to leave the machine translations behind and just take the ones that I did myself: https://github.com/alexhenrie/git-po/commits/es

@alexhenrie , thank you for your contributing. The helper program and myself cannot check the quality of the translations, but I know machine translation is far from perfect. I will follow the unanimous decision of both of you.

**Comment by alexhenrie** [comment]
@ChrisADR Would you be OK with using my translations for 2.38 instead of the machine translations?

**Comment by ChrisADR** [comment]
sure @alexhenrie, let's use your version, it's ok for me

**Comment by alexhenrie** [comment]
Thanks! I've opened a new pull request at https://github.com/git-l10n/git-po/pull/671

**Pull request closed without merging**
