### PR TITLE
SEE README: l10n: zh_TW.po: v2.32.0 round 1 (11 untranslated)

### PR DESCRIPTION
**Pull request by pan93412**
I'm still waiting for v2.32.0 round 2 so currently I prefer to leave it not merged until round 2 released and I completed translating round 2.

### CODE REVIEW

**Comment by jiangxin** [comment]
Please fixed the following errors found using [git-po-helper](https://github.com/git-l10n/git-po-helper).

```
[po/zh_TW.po] 5193 条已翻译消息，9 条模糊消息，2 条未翻译消息.
ERROR commit b00d7d2: subject is too long (82 > 62) 
ERROR commit 97e971a: do not have prefix "l10n:" in subject 
ERROR commit 97e971a: cannot find "Signed-off-by:" signature 
```

**Comment by pan93412** [comment]
> Please fixed the following errors found using [git-po-helper](https://github.com/git-l10n/git-po-helper).
> 
> ```
> [po/zh_TW.po] 5193 条已翻译消息，9 条模糊消息，2 条未翻译消息.
> ERROR commit 97e971a: do not have prefix "l10n:" in subject 
> ERROR commit 97e971a: cannot find "Signed-off-by:" signature 
> ```

I will check it later. Thanks for notifying me! :-)

**Comment by pan93412** [comment]
@jiangxin fixed. could you help me test it? [I'm unable to use `git-po-helper`.](https://github.com/git-l10n/git-po-helper/issues/1)

**Comment by jiangxin** [comment]
> @jiangxin fixed. could you help me test it? [I'm unable to use `git-po-helper`.](https://github.com/git-l10n/git-po-helper/issues/1)

Previous issues are fixed. Thanks.

**Comment by jiangxin** [comment]
> I'm still waiting for v2.32.0 round 2 so currently I prefer to leave it not merged until round 2 released and I completed translating round 2.

Git 2.32.0-rc2 was release, and nothing changed for `po/git.pot`.  So there will be no round 2 for l10n of git 2.32.0.

**Comment by pan93412** [comment]
> > I'm still waiting for v2.32.0 round 2 so currently I prefer to leave it not merged until round 2 released and I completed translating round 2.
> 
> Git 2.32.0-rc2 was release, and nothing changed for `po/git.pot`. So there will be no round 2 for l10n of git 2.32.0.

@jiangxin Could you help me merge it? Thanks! I have looked around with the currently untranslated strings and I still have no idea how to translate it elegantly.

**Comment by jiangxin** [comment]
> > > I'm still waiting for v2.32.0 round 2 so currently I prefer to leave it not merged until round 2 released and I completed translating round 2.
> > 
> > 
> > Git 2.32.0-rc2 was release, and nothing changed for `po/git.pot`. So there will be no round 2 for l10n of git 2.32.0.
> 
> @jiangxin Could you help me merge it? Thanks! I have looked around with the currently untranslated strings and I still have no idea how to translate it elegantly.

Will merge. Simplified Chinese translation has not started yet, I am very busy these days.

**Pull request merged**
