### PR TITLE
l10n: Initial Indonesian translation

### PR DESCRIPTION
**Pull request by bagasme**
This PR provides initial Indonesian translation (not completed yet)

Components translated:
  * `init-db`
  * `wt-status`
  * `builtin/clone`
  * `builtin/checkout`
  * `builtin/fetch`
  * Other core components:
    * `builtin/remote`
    * `builtin/index-pack`
    * `push`
    * `reset`

Note: Actually, there exists [WIP branch](https://github.com/git-l10n/git-po/tree/WIP/id%2Fanaufalm), but it seems stalled, so I have to restart from scratch.

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @bagasme , thank you for your contribution. There are some conventions for l10n contributors should follow:

1. The subject of each commit should have a fixed prefix: "l10n: ".  To see how other contributors wrote their commit log, running `git log --no-merges -- po/` .

2. The length of the subject of the commit log should less than 50, and the other lines (body of the commit log) should no more than 72 characters.

3. Add a "Signed-off-by" line in the trailer of the commit log like other commits of Git.  Create commit by running `git commit -s` will add a proper "s-o-b" trailer automatically.

4. Check and solve syntax errors of ".po" file using `msgfmt` command before sending pull request.

5. Squash trivial commits to make history clear.

6. Do not change files outside the `po/` directory.

7. Subprojects "git-gui" and "gitk" have their own workflow, DO NOT send pull request for these project here. See: `Documentation/SubmittingPatches`.

8. See our pull request archives for conventions of git l10n:

    + https://github.com/git-l10n/git-po/pulls?q=is%3Apr+is%3Aclosed+label%3Astyle%21

9. Take the leadership by providing an entry for your language in `po/TEAMS` file in a standalone commit. See pull request archives on this topic:

    + https://github.com/git-l10n/git-po/pulls?q=label%3Anew-team+is%3Aclosed

10. There is a l10n helper program for git at: https://github.com/git-l10n/git-po/blob/po-helper/utils/po-helper.sh.  It is just a wrapper on gettext utilities.  It may help for:

    + Update your `po/XX.po` by running:

            $ po-helper.sh update pl.po

        or using:

            $ msgmerge --add-location --backup=off -U po/pl.po po/git.pot

    + Check syntax errors and make sure the core part of l10n messages has been translated:

        $ po-helper.sh check id.po
        id.po     : 400 translated messages, 24 fuzzy translations, 4679 untranslated messages.
                    [gettext 0.14] ok
                    [core id] ................................................. done.
                    [core id] 282 translated messages, 199 untranslated messages.

**Comment by bagasme** [comment]
@jiangxin so for this PR i haven't yet added `l10n: ` prefix. Should I force-push?

**Comment by jiangxin** [comment]
> @jiangxin so for this PR i haven't yet added `l10n: ` prefix. Should I force-push?

The title of this PR does not matter.  Please squash your commits, change the commit log and make a force-push.

**Comment by bagasme** [comment]
ping

**Comment by jiangxin** [comment]
There are about 500 core l10n messages need to be translated completely. After running the following command:

    $ po-helper.sh check id.po

Two new files will be generated in the `po/` directory. Try to completed translation for the `po/core-XX.po` file and merge it to your `po/XX.po` file.

**Comment by bagasme** [comment]
@jiangxin so let's say i have completed `po/core-id.po`. how can i merge it back to `po/id.po`?

**Comment by jiangxin** [comment]
> @jiangxin so let's say i have completed `po/core-id.po`. how can i merge it back to `po/id.po`?

You can use `msgcat` to combine two po files.

**Comment by bagasme** [comment]
> > @jiangxin so let's say i have completed `po/core-id.po`. how can i merge it back to `po/id.po`?
> 
> You can use `msgcat` to combine two po files. `msgcat` is a utility of `gettext` package.

what order of argument should i passed to `msgcat`? `msgcat core-id.po id.po` or `msgcat id.po core-id.po`?

**Comment by bagasme** [comment]
ping

**Comment by jiangxin** [comment]
Will merge this weekend. According to [git calendar](https://calendar.google.com/calendar/u/0/embed?src=jfgbl2mrlipp4pb6ieih0qr3so@group.calendar.google.com&ctz=America/Los_Angeles), l10n update window will be closed at next monday.

**Pull request merged**
