### PR TITLE
l10n: es.po initial version

### PR DESCRIPTION
**Pull request by ChrisADR**
Initial version of spanish TEAM updated too

Christopher Díaz Riveros

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @ChrisADR , you can try to contact @nelson6e65. @nelson6e65 sent a [pull request](https://github.com/git-l10n/git-po/pull/190) one year before, and he had made some progress (see [this project](https://www.transifex.com/nelson6e65/git-po/)).

You commits also have the same issues as in [PR#190](https://github.com/git-l10n/git-po/pull/190).  I will create a WIP branch for you, and will merge when you complete it.

**Comment by ChrisADR** [comment]
Hi @jiangxin, thanks for the info. I'll email @nelson6e65 and see how is he going.

On the other hand, I'll keep working on this branch too,  I've noticed that some commits have both your signature and the author's one, do I need to sign it? or should I only follow the syntax? When I'm done, do you need me to rebase all the commits into a single one?

Thanks

**Comment by nelson6e65** [comment]
Hi.

Yes, I used the Transifex platform to translate and auto-build es.po.

https://www.transifex.com/nelson6e65/git-po/

https://github.com/nelson6e65/transifex-git

It's outdated currently, I need to perform a Sync. But not a lot of free time to translate full time. I'll check your state in this weekend.

I'll check my email to contact to you @ChrisADR Chri. :smile:

**Comment by jiangxin** [comment]
Hi @ChrisADR , signatures at the end of the commit show the review workflow of the commit. Author of the commit add his/her signature automatically by command "git commit -s".  And he/she or the committer will append other guy's signatures by hands.  You can see other signatures other than the "signed-off-by" form.

It is necessary to squash all trivial commits into one.  You can add all contributors' signature (contributed-by: line , maybe) and list contributors in the header of the po file.

**Comment by nelson6e65** [comment]
Hi, @jiangxin.

We, @ChrisADR and I, are working on Transifex. Its 54% translated already. 

We are going to open a new PR for the next release, from https://github.com/nelson6e65/git-po repo, with the reviewed :es: translation. 😄

**Pull request closed without merging**
