### PR TITLE
l10n: Start on Norwegian Bokmål translation with myself as "team leader"

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Completed the output for 'git status'.  It will take a while to get
through the entire set.

Signed-off-by: Petter Reinholdtsen <pere@hungry.com>

This started as #339, but when I fulfilled the request to rename the branch, that pull request was closed.

### CODE REVIEW

**Comment by jiangxin** [comment]
There is a l10n maintaince script in `po-helper` branch, see:

    https://github.com/git-l10n/git-po/tree/po-helper/utils

I create a new subcmd to generate a minimal pot file, See [this commit](https://github.com/git-l10n/git-po/commit/b29c8d544c5a987da3412e5ba52b6c3f2648f48b).

You can get the minimal l10n po file using this command:

    po-helper.sh essential nb.po

Please complete l10n of this minimal l10n template in pull request.

**Comment by petterreinholdtsen** [comment]
[Jiang Xin]
> Please complete l10n of this minimal l10n template in pull request.

Very good.  It will take a few days for me to get through the 403
strings.  I'll keep the git-l10n-nb updated with my progress.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by jiangxin** [comment]
Hi @petterreinholdtsen,

Before you send your final pull request, please note:

1. Subject of commit log has a soft limit of 50 characters according to `Documentation/SubmittingPatches`, and your commits have very long subjects. Please fix them.  You can see how other l10n contributers write commit log by command: `git log -- po/`.

2. Squash all trival commits into one commit for translation. If there are other contributers, add them in commit log signature, e.g. add a `Contributed-by:` line.

**Comment by jiangxin** [comment]
Hi @petterreinholdtsen,

Any progress?  There are some fixes waiting to be sent upstream.  If you can send pull request this week, I can wait.

**Comment by petterreinholdtsen** [comment]
[Jiang Xin]
> Any progress?  There are some fixes waiting to be sent upstream.  If
> you can send pull request this week, I can wait.

There is progress, but there are some phrases that are very hard to
translate (remote, track(ing)), so I have not been able to complete what
you set as the minimum amount.

I'll wrap up what I got as a simple commit, for you to have a look. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by jiangxin** [comment]
Hi, Git 2.21.0 release cycle will be close in 2 weeks. If all 423 essential entries are translated, please update this pull request.

As how to write commit log and update po/TEAMS file, see discussion in PR #345

**Pull request closed without merging**
