### PR TITLE
l10n: fr.po v2.11.0_rnd1

### PR DESCRIPTION
**Pull request by jnavila**
Signed-off-by: Jean-Noel Avila <jn.avila@free.fr>

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @jnavila and @jfbu ,

Commit 	f3910ab "i18n: fr.po fix grammar mistakes" has wrong prefix. Prefix "i18n" means
marking strings for translation in Git C code, and prefix "l10n" means translating messages
in "*.po" files.

So please correct it.

Thanks.

**Comment by jnavila** [comment]
Done

**Comment by jfbu** [comment]
@jnavila it should be ``dû`` at https://github.com/jnavila/git/blob/f3b52a72ebc29180978d4745ede133e304f9da27/po/fr.po#L6960, and on the other hand 

https://github.com/git-l10n/git-po/pull/202/commits/f3b52a72ebc29180978d4745ede133e304f9da27

should be reverted because the ``dû`` there was ok. IMHO ;-)

**Comment by jfbu** [comment]
also https://github.com/jnavila/git/blob/f3b52a72ebc29180978d4745ede133e304f9da27/po/fr.po#L14521, same issue

**Comment by jfbu** [comment]
sorry @jnavila I should have posted my comments on your fork. apologies as I am not familiar with the repos here.

**Comment by jnavila** [comment]
Hopefully OK this time!

**Pull request merged**
