### PR TITLE
l10n: bg.po: Updated Bulgarian translation (5227t)

### PR DESCRIPTION
**Pull request by alshopov**
Signed-off-by: Alexander Shopov <ash@kambanaria.org>

### CODE REVIEW

**Comment by jiangxin** [comment]
Andrei pointed out a typo in the Swedish translation, where a config variable name had been copied incorrectly. I introduced new checks in `git-po-helper`, and found many typos in `po/*.po`.  See our discussions in [this thread](https://lore.kernel.org/git/20210703111837.14894-1-worldhello.net@gmail.com/).

Please fix typos in `po/bg.po` like others:
* [l10n: id.po: fix mismatched variable names](https://github.com/git-l10n/git-po/commit/f3abf6aa6367a51e76aa837b9df5fc0986d25f4d)
* [l10n: fixed typos of mismatched constant strings](https://github.com/git-l10n/git-po/commit/ae4e099e7cd2fcb7abdcce1b4fe02b40d5e4a61b)

Typos found by `git-po-helper`:

```
[po/bg.po]    5227 translated messages.
level=warning msg="mismatch variable names in msgstr: extensions.partialclone"
level=warning msg=">> msgid: --filter can only be used with the remote configured in extensions.partialclone"
level=warning msg=">> msgstr: опцията „--filter“ може да се ползва само с отдалеченото хранилище указано в настройката „extensions.partialClone“"
level=warning
level=warning msg="mismatch variable names in msgstr: credential-cache--daemon"
level=warning msg=">> msgid: credential-cache--daemon unavailable; no unix socket support"
level=warning msg=">> msgstr: демонът за кеша с идентификациите е недостъпен — липсва поддръжка на гнезда на unix"
level=warning
level=warning msg="mismatch variable names in msgstr: crlf_action"
level=warning msg=">> msgid: illegal crlf_action %d"
level=warning msg=">> msgstr: неправилно действие за край на ред: %d"
level=warning
level=warning msg="mismatch variable names in msgstr: s.merge"
level=warning msg=">> msgid: invalid branch.%s.merge; cannot rebase onto > 1 branch"
level=warning msg=">> msgstr: неправилен клон за сливане „%s“.  Невъзможно е да пребазирате върху повече от 1 клон"
level=warning
level=warning msg="mismatch variable names in msgstr: run_command"
level=warning msg=">> msgid: run_command returned non-zero status for %s\n."
level=warning msg=">> msgstr: изпълнената команда завърши с ненулев изход за „%s“\n."
level=warning
level=warning msg="mismatch variable names in msgstr: run_command"
level=warning msg=">> msgid: run_command returned non-zero status while recursing in the nested submodules of %s\n."
level=warning msg=">> msgstr: изпълнената команда завърши с ненулев изход при обхождане на подмодулите, вложени в „%s“\n."
level=warning
level=warning msg="mismatch variable names in msgstr: lazy_dir"
level=warning msg=">> msgid: unable to create lazy_dir thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за директории: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: lazy_name"
level=warning msg=">> msgid: unable to create lazy_name thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за имена: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: load_cache_entries"
level=warning msg=">> msgid: unable to create load_cache_entries thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за зареждане на обектите от кеша: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: load_index_extensions"
level=warning msg=">> msgid: unable to create load_index_extensions thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за зареждане на разширенията на индекса: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: lazy_name"
level=warning msg=">> msgid: unable to join lazy_name thread: %s"
level=warning msg=">> msgstr: не може да се изчака нишка за имена: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: load_cache_entries"
level=warning msg=">> msgid: unable to join load_cache_entries thread: %s"
level=warning msg=">> msgstr: не може да се изчака нишка за зареждане на обектите от кеша: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: load_index_extensions"
level=warning msg=">> msgid: unable to join load_index_extensions thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за зареждане на разширенията на индекса: %s"
level=warning
level=warning msg="mismatch variable names in msgstr: new_index"
level=warning msg=">> msgid: unable to write new_index file"
level=warning msg=">> msgstr: новият индекс не може да бъде записан"
level=warning
level=warning msg="mismatch variable names in msgstr: update_ref"
level=warning msg=">> msgid: update_ref failed for ref '%s': %s"
level=warning msg=">> msgstr: неуспешно обновяване на указателя „%s“: %s"
level=warning
```

**Comment by jiangxin** [comment]
More typos will be found using `git-po-helper` v0.0.6:

```
level=warning msg="mismatch variable names in msgstr: $HOME"
level=warning msg=">> msgid: $HOME not set"
level=warning msg=">> msgstr: променливата „HOME“ не е зададена"
level=warning 
level=warning msg="mismatch variable names in msgstr: $sm_path"
level=warning msg=">> msgid: '$sm_path' already exists and is not a valid git repo"
level=warning msg=">> msgstr: „${sm_path}“ съществува, а не е хранилище на Git"
level=warning 
level=warning msg="mismatch variable names in msgstr: $sm_path"
level=warning msg=">> msgid: '$sm_path' already exists in the index"
level=warning msg=">> msgstr: „${sm_path}“ вече съществува в индекса"
level=warning 
level=warning msg="mismatch variable names in msgstr: $sm_path"
level=warning msg=">> msgid: '$sm_path' already exists in the index and is not a submodule"
level=warning msg=">> msgstr: „${sm_path}“ вече съществува в индекса и не е подмодул"

... ...
```

**Comment by alshopov** [comment]
Hi Jiang Xin,

I do not agree with your assessment of what is typo or not.
For example the message:

level=warning msg="mismatch variable names in msgstr: update_ref"
level=warning msg=">> msgid: update_ref failed for ref '%s': %s"
level=warning msg=">> msgstr: неуспешно обновяване на указателя „%s“: %s"

update_ref is not a variable - it is a function that updates
references. The message "update_ref failed" is bad.
The user is interested in the fact that the update of the reference
failed rather than in the fact that a particular function failed.

If you insist on this I think I can appease your linter by adding the
requested char sequence in parentheses. It will not do much harm
besides making the message longer.

However not so with the examples of shell variables. There is a
difference between HOME which is the variable (its name) and $HOME
which is its value.

Whenever we talk about setting the variable - we use HOME, rather than
$HOME (you set it via HOME=/bin, ratther than $HOME=/bin)

Additionally ${sm_path} is a safer alternative -
- echo ${sm_path}FOO works while
- echo $sm_pathFOO does not

Are you making passing the git-po-helper linter a hard requirement?
I've missed the discussion in the git mail list.

Kind regards:
al_shopov


На сб, 7.08.2021 г. в 17:31 ч. Jiang Xin ***@***.***> написа:

**Comment by jiangxin** [comment]
`git-po-helper` is a helper program, and the typos it suggested are suggestion. Some typos are real problems you should take care, for example the following new typos found by `git-po-helper` v0.2.0:

* `$HOME` is a shell variable, and will expand to real directory, but if missing the `$` prefix, no variable expansion.

```
level=warning msg="mismatch variable names: $HOME"
level=warning msg=">> msgid: $HOME not set"
level=warning msg=">> msgstr: променливата „HOME“ не е зададена"
```

* Can you keep the angle brackets ( `<...>` ), so pattern matching works for your language. This is because normal regex matching not works for some languages, such as Vietnamese. See this commit : https://github.com/git-l10n/git-po-helper/commit/dd24c0067d533bb432a6d3a8fbe89f4547b6c796

```
level=warning msg="mismatch variable names: --git-dir=, --work-tree="
level=warning msg=">> msgid: %s (or --work-tree=<directory>) not allowed without specifying %s (or --git-dir=<directory>)"
level=warning msg=">> msgstr: %s (или --work-tree=ДИРЕКТОРИЯ) изисква указването на %s (или --git-dir=ДИРЕКТОРИЯ)"
```

* I will try to program to ignore the following case, treate `${var}` just like `$var`.  For my language, withBut add space around it is normal for my language, and

**Comment by jiangxin** [comment]
`git-po-helper` is a helper program, and the typos it suggested are ONLY suggestions. Some typos are real problems you should take care, I will try to minimize false positives. If the following is not a issue, I can stop scan typos for some languages or stop scanning all.

* `$HOME` is a shell variable, and will expand to real directory, but if missing the `$` prefix, no variable expansion.

```
level=warning msg="mismatch variable names: $HOME"
level=warning msg=">> msgid: $HOME not set"
level=warning msg=">> msgstr: променливата „HOME“ не е зададена"
```

* Can you keep the angle brackets ( `<...>` ), so pattern matching works for your language. This is because normal regex matching not works for some languages, such as Vietnamese. See this commit : https://github.com/git-l10n/git-po-helper/commit/dd24c0067d533bb432a6d3a8fbe89f4547b6c796

```
level=warning msg="mismatch variable names: --git-dir=, --work-tree="
level=warning msg=">> msgid: %s (or --work-tree=<directory>) not allowed without specifying %s (or --git-dir=<directory>)"
level=warning msg=">> msgstr: %s (или --work-tree=ДИРЕКТОРИЯ) изисква указването на %s (или --git-dir=ДИРЕКТОРИЯ)"
```

* I will try to program to ignore the following case, treate `${var}` just like `$var`.  For my language, it is strange that no spaces around a variable.

```
level=warning msg="mismatch variable names: $sm_path, ${sm_path}"
level=warning msg=">> msgid: '$sm_path' already exists in the index"
level=warning msg=">> msgstr: „${sm_path}“ вече съществува в индекса"
```

* If you translate the option name, `git-po-helper` will never again find mismatch for it:

```
level=warning msg="mismatch variable names: --abort"
level=warning msg=">> msgid: --abort but leave index and working tree alone"
level=warning msg=">> msgstr: преустановяване без промяна на индекса и работното дърво"

level=warning msg="mismatch variable names: --no-contains"
level=warning msg=">> msgid: --no-contains option is only allowed in list mode"
level=warning msg=">> msgstr: опцията „-contains“ изисква  режим на списък."
level=warning
```

* Real typos?

```
level=warning msg="mismatch variable names: --reflog, --track"
level=warning msg=">> msgid: --reflog option needs one branch name"
level=warning msg=">> msgstr: опцията „--track“ изисква точно едно име на клон"

level=warning msg="mismatch variable names: --quit, --skip"
level=warning msg=">> msgid: git am [<options>] (--continue | --skip | --abort)"
level=warning msg=">> msgstr: git am [ОПЦИЯ…] (--continue | --quit | --abort)"

level=warning msg="mismatch variable names: --bisect-next, --bisect-replay"
level=warning msg=">> msgid: git bisect--helper --bisect-replay <filename>"
level=warning msg=">> msgstr: git bisect--helper --bisect-next ИМЕ_НА_ФАЙЛ"

level=warning msg="mismatch variable names: --bisect-reset, --bisect-skip"
level=warning msg=">> msgid: git bisect--helper --bisect-skip [(<rev>|<range>)...]"
level=warning msg=">> msgstr: git bisect--helper --bisect-reset [(ВЕРСИЯ|ДИАПАЗОН)…]"

level=warning msg="mismatch variable names: --bisect-reset, --bisect-state"
level=warning msg=">> msgid: git bisect--helper --bisect-state (bad|new) [<rev>]"
level=warning msg=">> msgstr: git bisect--helper --bisect-reset (ЛОШО) [ВЕРСИЯ]"

level=warning msg="mismatch variable names: --no-index"
level=warning msg=">> msgid: git mailinfo [<options>] <msg> <patch> < mail >info"
level=warning msg=">> msgstr: git mailinfo [ОПЦИЯ…] СЪОБЩЕНИЕ КРЪПКА < ПИСМО >ИНФОРМАЦИЯ\ngit diff --no-index  ПЪТ ПЪТ"
```

**Comment by jiangxin** [comment]
You can use v0.2.0 version of `git-po-helper` to find real typos among many false positives.  Tell me it is ok to merge your PR.

Thanks.

**Comment by jiangxin** [comment]
Sorry, may be I click the wrong button. Reopen again. ;)

**Comment by jiangxin** [comment]
New commits for `git-po-helper` to minimize false positives:

* https://github.com/git-l10n/git-po-helper/commit/0cb51762478d5adba0f672f05726f52d1195f44b
* https://github.com/git-l10n/git-po-helper/commit/a9b8a06f81fd931936ce88dead758df71b3cae7a

Many false positives warnings are suppressed. Still there are some warnings:

## May be typos: lost '$' prefix of a shell variable

```
level=warning msg="mismatch variable names: $HOME"
level=warning msg=">> msgid: $HOME not set"
level=warning msg=">> msgstr: променливата „HOME“ не е зададена"
```


## Typos: should be "--", not "-"

```
level=warning msg="mismatch variable names: --contains"
level=warning msg=">> msgid: --contains option is only allowed in list mode"
level=warning msg=">> msgstr: опцията „-contains“ изисква режим на списък."

level=warning msg="mismatch variable names: --points-at"
level=warning msg=">> msgid: --points-at option is only allowed in list mode"
level=warning msg=">> msgstr: опцията „-points-at“ изисква режим на списък."

level=warning msg="mismatch variable names: --rfc"
level=warning msg=">> msgid: --subject-prefix/--rfc and -k are mutually exclusive"
level=warning msg=">> msgstr: опциите „--subject-prefix“/„-rfc“ и „-k“ са несъвместими"

level=warning msg="mismatch variable names: --stdin"
level=warning msg=">> msgid: --stdin and --merge-base are mutually exclusive"
level=warning msg=">> msgstr: опциите „-stdin“ и „--merge-base“ са несъвместими"

level=warning msg="mismatch variable names: --filter"
level=warning msg=">> msgid: cannot use --filter with --stdin-packs"
level=warning msg=">> msgstr: опциите „-filter“ и „--stdin-packs“ са несъвместими"

level=warning msg="mismatch variable names: --filter, --stdout"
level=warning msg=">> msgid: cannot use --filter without --stdout"
level=warning msg=">> msgstr: опцията „-filter“ изисква „-stdout“"

```


## Typos: wrong translation or unmatched cases?

```
level=warning msg="mismatch variable names: --no-contains"
level=warning msg=">> msgid: --no-contains option is only allowed in list mode"
level=warning msg=">> msgstr: опцията „-contains“ изисква  режим на списък."

level=warning msg="mismatch variable names: --cached, --no-index"
level=warning msg=">> msgid: --no-index or --untracked cannot be used with revs"
level=warning msg=">> msgstr: опциите „--cached“ и „--untracked“ са несъвместими с версии."

level=warning msg="mismatch variable names: --reflog, --track"
level=warning msg=">> msgid: --reflog option needs one branch name"
level=warning msg=">> msgstr: опцията „--track“ изисква точно едно име на клон"

level=warning msg="mismatch variable names: --name-only, --only-input"
level=warning msg=">> msgid: --trailer with --only-input does not make sense"
level=warning msg=">> msgstr: опцията „--trailer“ е несъвместима с „--name-only“"

level=warning msg="mismatch variable names: --worktre, --worktree"
level=warning msg=">> msgid: --worktree cannot be used with multiple working trees unless the config\nextension worktreeConfig is enabled. Please read \"CONFIGURATION FILE\"\nsection in \"git help worktree\" for details"
level=warning msg=">> msgstr: опцията „--worktre“ не приема множество работни дървета, преди\nвключването на разширението в настройките „worktreeConfig“.  За\nповече информация вижте раздела „CONFIGURATION FILE“ в\n„git help worktree“"

level=warning msg="mismatch variable names: --no-commit"
level=warning msg=">> msgid: Automatic merge went well; stopped before committing as requested\n"
level=warning msg=">> msgstr: Автоматичното сливане завърши успешно.  Самото подаване не е извършено, защото бе зададена опцията „--no-commit“.\n"

level=warning msg="mismatch variable names: $BRANCH, $br"
level=warning msg=">> msgid: Git normally never creates a ref that ends with 40 hex characters\nbecause it will be ignored when you just specify 40-hex. These refs\nmay be created by mistake. For example,\n\n  git switch -c $br $(git rev-parse ...)\n\nwhere \"$br\" is somehow empty and a 40-hex ref is created. Please\nexamine these refs and maybe delete them. Turn this message off by\nrunning \"git config advice.objectNameWarning false\""
level=warning msg=">> msgstr: При нормална работа Git никога не създава указатели, които завършват\nс 40 шестнадесетични знака, защото стандартно те ще бъдат прескачани.\nВъзможно е такива указатели да са създадени случайно.  Например:\n\n    git switch -c $BRANCH $(git rev-parse …)\n\nкъдето стойността на променливата на средата BRANCH е празна, при което\nсе създава подобен указател.  Прегледайте тези указатели и ги изтрийте.\nЗа да изключите това съобщение, изпълнете:\n\n    git config advice.objectNameWarning false"

level=warning msg="mismatch variable names: --no-ff"
level=warning msg=">> msgid: Non-fast-forward commit does not make sense into an empty head"
level=warning msg=">> msgstr: Понеже върхът е без история, всички сливания са превъртания, не може да се извърши същинско сливане изисквано от опцията „--no-ff“"

level=warning msg="mismatch variable names: --update"
level=warning msg=">> msgid: bad value for update parameter"
level=warning msg=">> msgstr: неправилен параметър към опцията „--update“"

level=warning msg="mismatch variable names: --quit, --skip"
level=warning msg=">> msgid: git am [<options>] (--continue | --skip | --abort)"
level=warning msg=">> msgstr: git am [ОПЦИЯ…] (--continue | --quit | --abort)"

level=warning msg="mismatch variable names: --bisect-next, --bisect-replay"
level=warning msg=">> msgid: git bisect--helper --bisect-replay <filename>"
level=warning msg=">> msgstr: git bisect--helper --bisect-next ИМЕ_НА_ФАЙЛ"

level=warning msg="mismatch variable names: --bisect-reset, --bisect-skip"
level=warning msg=">> msgid: git bisect--helper --bisect-skip [(<rev>|<range>)...]"
level=warning msg=">> msgstr: git bisect--helper --bisect-reset [(ВЕРСИЯ|ДИАПАЗОН)…]"

level=warning msg="mismatch variable names: --bisect-reset, --bisect-state"
level=warning msg=">> msgid: git bisect--helper --bisect-state (bad|new) [<rev>]"
level=warning msg=">> msgstr: git bisect--helper --bisect-reset (ЛОШО) [ВЕРСИЯ]"

level=warning msg="mismatch variable names: --bisect-reset, --bisect-state"
level=warning msg=">> msgid: git bisect--helper --bisect-state (good|old) [<rev>...]"
level=warning msg=">> msgstr: git bisect--helper --bisect-reset (ДОБРО) [ВЕРСИЯ…]"

level=warning msg="mismatch variable names: git upload-pack, git upload-repack"
level=warning msg=">> msgid: git upload-pack [<options>] <dir>"
level=warning msg=">> msgstr: git upload-repack [ОПЦИЯ…] ДИРЕКТОРИЯ"

level=warning msg="mismatch variable names: git verify-commit, git verify-tag"
level=warning msg=">> msgid: git verify-commit [-v | --verbose] <commit>..."
level=warning msg=">> msgstr: git verify-tag [-v | --verbose] ПОДАВАНЕ…"

level=warning msg="mismatch variable names: conclude_pack"
level=warning msg=">> msgid: confusion beyond insanity"
level=warning msg=">> msgstr: фатална грешка във функцията „conclude_pack“.  Това е грешка в Git, докладвайте я на разработчиците, като пратите е-писмо на адрес: „git@vger.kernel.org“."

level=warning msg="mismatch variable names: --raw, --stat"
level=warning msg=">> msgid: synonym for '-p --raw'"
level=warning msg=">> msgstr: псевдоним на „-p --stat“"

level=warning msg="mismatch variable names: git cherry-pick"
level=warning msg=">> msgid: try \"git revert (--continue | %s--abort | --quit)\""
level=warning msg=">> msgstr: използвайте „git cherry-pick (--continue | %s--abort | --quit)“"
level=warning

level=warning msg="mismatch variable names: s.merge"
level=warning msg=">> msgid: invalid branch.%s.merge; cannot rebase onto > 1 branch"
level=warning msg=">> msgstr: неправилен клон за сливане „%s“.  Невъзможно е да пребазирате върху повече от 1 клон"

level=warning msg="mismatch variable names: dimmed_zebra"
level=warning msg=">> msgid: color moved setting must be one of 'no', 'default', 'blocks', 'zebra', 'dimmed-zebra', 'plain'"
level=warning msg=">> msgstr: настройката за цвят за преместване трябва да е една от: „no“ (без), „default“ (стандартно), „blocks“ (парчета), „zebra“ (райе), „dimmed_zebra“ (тъмно райе), „plain“ (обикновено)"

level=warning msg="mismatch variable names: extensions.partialClone, extensions.partialclone"
level=warning msg=">> msgid: --filter can only be used with the remote configured in extensions.partialclone"
level=warning msg=">> msgstr: опцията „--filter“ може да се ползва само с отдалеченото хранилище указано в настройката „extensions.partialClone“"
```

## If keep the angle brackets (`<...>`), can suppress these false positive warnings
 
```
level=warning msg="mismatch variable names: --git-dir=, --work-tree="
level=warning msg=">> msgid: %s (or --work-tree=<directory>) not allowed without specifying %s (or --git-dir=<directory>)"
level=warning msg=">> msgstr: %s (или --work-tree=ДИРЕКТОРИЯ) изисква указването на %s (или --git-dir=ДИРЕКТОРИЯ)"

level=warning msg="mismatch variable names: --unpacked="
level=warning msg=">> msgid: --unpacked=<packfile> no longer supported"
level=warning msg=">> msgstr: опцията „--unpacked=ПАКЕТЕН_ФАЙЛ“ вече не се поддържа"

level=warning msg="mismatch variable names: --prefix="
level=warning msg=">> msgid: git read-tree [(-m [--trivial] [--aggressive] | --reset | --prefix=<prefix>) [-u [--exclude-per-directory=<gitignore>] | -i]] [--no-sparse-checkout] [--index-output=<file>] (--empty | <tree-ish1> [<tree-ish2> [<tree-ish3>]])"
level=warning msg=">> msgstr: git read-tree [(-m [--trivial] [--aggressive] | --reset | --prefix=ПРЕФИКС) [-u [--exclude-per-directory=ФАЙЛ_С_ИЗКЛЮЧЕНИЯ] | -i]] [--no-sparse-checkout] [--index-output=ФАЙЛ] (--empty | УКАЗАТЕЛ_КЪМ_ДЪРВО_1 [УКАЗАТЕЛ_КЪМ_ДЪРВО_2 [УКАЗАТЕЛ_КЪМ_ДЪРВО_3]])"

level=warning msg="mismatch variable names: --config="
level=warning msg=">> msgid: missing --config=<config>"
level=warning msg=">> msgstr: липсва --config=НАСТРОЙКА"

level=warning msg="mismatch variable names: --extcmd="
level=warning msg=">> msgid: no <cmd> given for --extcmd=<cmd>"
level=warning msg=">> msgstr: не е зададена команда за „--extcmd=КОМАНДА“"

level=warning msg="mismatch variable names: --tool="
level=warning msg=">> msgid: no <tool> given for --tool=<tool>"
level=warning msg=">> msgstr: не е зададена програма за „--tool=ПРОГРАМА“"

level=warning msg="mismatch variable names: --schedule="
level=warning msg=">> msgid: use at most one of --auto and --schedule=<frequency>"
level=warning msg=">> msgstr: може да се указва максимум една от опциите „--auto“ и „--schedule=ЧЕСТОТА“"

level=warning msg="mismatch variable names: --word-diff-regex="
level=warning msg=">> msgid: equivalent to --word-diff=color --word-diff-regex=<regex>"
level=warning msg=">> msgstr: псевдоним на „--word-diff=color --word-diff-regex=РЕГУЛЯРЕН_ИЗРАЗ“"

level=warning msg="mismatch variable names: --config="
level=warning msg=">> msgid: git for-each-repo --config=<config> <command-args>"
level=warning msg=">> msgstr: git for-each-repo --config=НАСТРОЙКА АРГУМЕНТ…"

```


## If use ascii instead of unicode characters as user part of a email address, can suppress these warnings

Is it valid to use unicode characters as user part of a email address?

```
level=warning msg="mismatch variable names: example.com"
level=warning msg=">> msgid: \n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email \"you@example.com\"\n  git config --global user.name \"Your Name\"\n\nto set your account's default identity.\nOmit --global to set the identity only in this repository.\n\n"
level=warning msg=">> msgstr: \n●●● Въведете самоличност.\n\nИзпълнете:\n\n    git config --global user.email \"ИМЕ@example.com\"\n    git config --global user.name \"ВАШЕТО ИМЕ\"\n\nи въведете данни за себе си.\nАко пропуснете опцията „--global“, самоличността е само за текущото хранилище.\n\n"

level=warning msg="mismatch variable names: example.com"
level=warning msg=">> msgid: Your name and email address were configured automatically based\non your username and hostname. Please check that they are accurate.\nYou can suppress this message by setting them explicitly:\n\n    git config --global user.name \"Your Name\"\n    git config --global user.email you@example.com\n\nAfter doing this, you may fix the identity used for this commit with:\n\n    git commit --amend --reset-author\n"
level=warning msg=">> msgstr: Името и адресът за е-поща са настроени автоматично на базата на името на\nпотребителя и името на машината.  Проверете дали са верни.  Може да спрете\nтова съобщение като изрично зададете стойностите:\n\n    git config --global user.name \"Вашето Име\"\n    git config --global user.email пенчо@example.com\n\nСлед като направите това, може да коригирате информацията за автора на\nтекущото подаване чрез:\n\n    git commit --amend --reset-author\n"

```


## Is is possible to contribute a patch to upstream? Or use as is

```
level=warning msg="mismatch variable names: --hard, --mixed, --soft"
level=warning msg=">> msgid: --patch is incompatible with --{hard,mixed,soft}"
level=warning msg=">> msgstr: опцията „--patch“ е несъвместима с всяка от опциите „--hard“/„--mixed“/„--soft“"

level=warning msg="mismatch variable names: git merge-base"
level=warning msg=">> msgid: use 'merge-base --fork-point' to refine upstream"
level=warning msg=">> msgstr: за доуточняването на следения клон, използвайте:\n\n    git merge-base --fork-point"

level=warning msg="mismatch variable names: --no-index"
level=warning msg=">> msgid: git mailinfo [<options>] <msg> <patch> < mail >info"
level=warning msg=">> msgstr: git mailinfo [ОПЦИЯ…] СЪОБЩЕНИЕ КРЪПКА < ПИСМО >ИНФОРМАЦИЯ\ngit diff --no-index  ПЪТ ПЪТ"

level=warning msg="mismatch variable names: git pack-objects"
level=warning msg=">> msgid: pack-objects died"
level=warning msg=">> msgstr: Командата „git pack-objects“ не завърши успешно"
level=warning
level=warning msg="mismatch variable names: git rev-list"
level=warning msg=">> msgid: ref '%s' is excluded by the rev-list options"
level=warning msg=">> msgstr: указателят „%s“ не е бил включен поради опциите зададени на „git rev-list“"

level=warning msg="mismatch variable names: git pack-objects"
level=warning msg=">> msgid: Could not spawn pack-objects"
level=warning msg=">> msgstr: Командата „git pack-objects“ не може да бъде стартирана"

level=warning msg="mismatch variable names: git-am"
level=warning msg=">> msgid: It looks like 'git am' is in progress. Cannot rebase."
level=warning msg=">> msgstr: Изглежда, че сега се прилагат кръпки чрез командата „git-am“.  Не може да пребазирате в момента."

level=warning msg="mismatch variable names: git-difftool"
level=warning msg=">> msgid: difftool requires worktree or --no-index"
level=warning msg=">> msgstr: „git-difftool“ изисква работно дърво или опцията „--no-index“"
```

## Possible false positives

```
level=warning msg="mismatch variable names: --bare"
level=warning msg=">> msgid: create a mirror repository (implies bare)"
level=warning msg=">> msgstr: създаване на хранилище-огледало (включва опцията „--bare“ за голо хранилище)"

level=warning msg="mismatch variable names: credential-cache--daemon"
level=warning msg=">> msgid: credential-cache--daemon unavailable; no unix socket support"
level=warning msg=">> msgstr: демонът за кеша с идентификациите е недостъпен — липсва поддръжка на гнезда на unix"

level=warning msg="mismatch variable names: run_command"
level=warning msg=">> msgid: run_command returned non-zero status for %s\n."
level=warning msg=">> msgstr: изпълнената команда завърши с ненулев изход за „%s“\n."

level=warning msg="mismatch variable names: run_command"
level=warning msg=">> msgid: run_command returned non-zero status while recursing in the nested submodules of %s\n."
level=warning msg=">> msgstr: изпълнената команда завърши с ненулев изход при обхождане на подмодулите, вложени в „%s“\n."

level=warning msg="mismatch variable names: --dirstat=files"
level=warning msg=">> msgid: synonym for --dirstat=files,param1,param2..."
level=warning msg=">> msgstr: псевдоним на „--dirstat=ФАЙЛОВЕ,ПАРАМЕТЪР_1,ПАРАМЕТЪР_2,…“"

level=warning msg="mismatch variable names: lazy_dir"
level=warning msg=">> msgid: unable to create lazy_dir thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за директории: %s"

level=warning msg="mismatch variable names: lazy_name"
level=warning msg=">> msgid: unable to create lazy_name thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за имена: %s"

level=warning msg="mismatch variable names: load_cache_entries"
level=warning msg=">> msgid: unable to create load_cache_entries thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за зареждане на обектите от кеша: %s"

level=warning msg="mismatch variable names: load_index_extensions"
level=warning msg=">> msgid: unable to create load_index_extensions thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за зареждане на разширенията на индекса: %s"

level=warning msg="mismatch variable names: lazy_name"
level=warning msg=">> msgid: unable to join lazy_name thread: %s"
level=warning msg=">> msgstr: не може да се изчака нишка за имена: %s"

level=warning msg="mismatch variable names: load_cache_entries"
level=warning msg=">> msgid: unable to join load_cache_entries thread: %s"
level=warning msg=">> msgstr: не може да се изчака нишка за зареждане на обектите от кеша: %s"

level=warning msg="mismatch variable names: load_index_extensions"
level=warning msg=">> msgid: unable to join load_index_extensions thread: %s"
level=warning msg=">> msgstr: не може да се създаде нишка за зареждане на разширенията на индекса: %s"

level=warning msg="mismatch variable names: new_index"
level=warning msg=">> msgid: unable to write new_index file"
level=warning msg=">> msgstr: новият индекс не може да бъде записан"

level=warning msg="mismatch variable names: --patch"
level=warning msg=">> msgid: unknown --patch mode: %s"
level=warning msg=">> msgstr: неизвестна стратегия за прилагане на кръпка: „%s“"

level=warning msg="mismatch variable names: --mirror"
level=warning msg=">> msgid: unknown mirror argument: %s"
level=warning msg=">> msgstr: неправилна стойност за „--mirror“: %s"

level=warning msg="mismatch variable names: update_ref"
level=warning msg=">> msgid: update_ref failed for ref '%s': %s"
level=warning msg=">> msgstr: неуспешно обновяване на указателя „%s“: %s"
```

**Comment by jiangxin** [comment]
Hi @alshopov 

Please note that the 2nd round of git l10n for git 2.33 has started, and the l10n window will be closed this Sunday. I'm sorry for sending this notice a bit late, send new pull request before the end of this Sunday.

Thanks.

**Pull request merged**
