### PR TITLE
l10n: sv.po: Fix git-po-helper breakage

### PR DESCRIPTION
**Pull request by nafmo**
Fixes errors introduced in commit efedbb11de27a22cf9d4c75255057716f0b1b8ce
when running git-po-helper.

Signed-off-by: Peter Krefting <peter@softwolves.pp.se>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
To resolve the following issue,

```
ERROR commit e9c45b9: commit log message is too long (74 > 72) 
```

you can reference a commit using the output of command, instead of using full 40-digit commit ID which make a line with characters more than 72:

```shell
$ git log -1 --pretty=reference efedbb11de27a22cf9d4c75255057716f0b1b8ce | cat 
efedbb11de (l10n: sv.po: Update Swedish translation (5230t0f0u), 2021-08-14)
```

**Comment by pan93412** [comment]
BTW, thanks @jiangxin for developing this tool ;) It helps me discovered a lot of typo & issues :)

**Comment by jiangxin** [comment]
> BTW, thanks @jiangxin for developing this tool ;) It helps me discovered a lot of typo & issues :)

Thanks @pan93412 .  I will contribute a new github action upstream, and github action can work automatically for us.

**Comment by pan93412** [comment]
> > BTW, thanks @jiangxin for developing this tool ;) It helps me discovered a lot of typo & issues :)
> 
> Thanks @pan93412 . I will contribute a new github action upstream, and github action can work automatically for us.

Great! I used to think to set up a GitHub Action for it, but gave up as it will affect something.

**Comment by jiangxin** [comment]
> To resolve the following issue,
> 
> ```
> ERROR commit e9c45b9: commit log message is too long (74 > 72) 
> ```
> 
> you can reference a commit using the output of the following command, instead of using full 40-digit commit ID which make a line with more than 72 characters:
> 
> ```shell
> $ git log -1 --pretty=reference efedbb11de27a22cf9d4c75255057716f0b1b8ce
> efedbb11de (l10n: sv.po: Update Swedish translation (5230t0f0u), 2021-08-14)
> ```

Hi @nafmo , can you edit your commit log, use the output of `git log --pretty=reference -1 <commit>` to replace the full oid which cannot wrap to new line easily.

**Pull request merged**
