### PR TITLE
Update the Italian translation

### PR DESCRIPTION
**Pull request by AlessandroMenti**
This is a first iteration of the (revised) Italian translation for Git.

Since the amount of strings to translate/update is pretty high, I'm submitting a first version now to release it early and I'll send more pull requests as I make progress.

### CODE REVIEW

**Comment by jiangxin** [comment]
L10n for Italian  hasn't been updated since commit tags/v1.7.11~2^2  (l10n: it.po: translate 212 new messages, 2012-06-14), and thank you for picking it up.

You can update the `po/TEAMS` file, and lead the l10n team. Before that, you can send a email to inform other team members.

If there are further updates before this week end, please squash them into one commit in this pull request.  I will mege it this Saturday.

**Comment by AlessandroMenti** [comment]
@jiangxin I've already updated the `TEAMS` file and informed the former team members before starting my work.

Should I manage to translate more strings, I'll update the branch and squash the commits.

**Comment by jiangxin** [comment]
Please fix these issues:

1. Subject of your commit log should have the prefix "l10n: it: " like other commits for `po/`, you can see how other l10n contributors write commit log.

2. Please add a "signed-off-by: " line in your commit log by committing with command `git commit -s`.

3. Say thank you in the header of your "po/it.po", and add former l10n contributors there instead of `po/TEAMS` file.

**Comment by AlessandroMenti** [comment]
@jiangxin Done!

**Comment by jiangxin** [comment]
I cherry-picked your commit, please reset your local branch. It is because I find your pull request  has commit from other l10n team. You signed Jordi's commit using your pgp key, plese do not touch other people's commit.

I'm not sure signing commit using gpg is a best practise or not. You can see commit log of git using `git log --show-signature`,  you will find signing commit using pgp is rare in git.git project, and only tags are signed using pgp.

**Pull request closed without merging**
