### PR TITLE
l10n: es.po: initial Spanish version for git 2.14.0

### PR DESCRIPTION
**Pull request by ChrisADR**
Initial version from git es language with 100% translation

### CODE REVIEW

**Comment by nelson6e65** [comment]
:sweat_smile:

**Comment by jiangxin** [comment]
Hi @ChrisADR , please update `po/TEAMS` file in a new commit to help other contributors sending PR to you.

**Comment by ChrisADR** [comment]
Done @jiangxin, any other thing that needs to be done?

**Comment by jiangxin** [comment]
merged into maint branch.

**Pull request closed without merging**
