### PR TITLE
l10n: es: Correct, disambiguate, and harmonize confusing terms

### PR DESCRIPTION
**Pull request by alexhenrie**
In this round, I am only harmonizing terms that could be confused for other terms:

* "arreglar" is not a good translation for "amend" because it can be confused with "fixup"
* "conjunto" is not a good translation for "chunk" because it can be confused with "bundle"
* "limpiar" is not a good translation for "prune" because it can be confused with "git clean"
* "enviar" is not a good translation for "push" because it can be confused with "send email"
* "renombrar" is not a good translation for "reword" because it can be confused with "rename"
* "fusionar" is not a good translation for "squash" because it can be confused with "merge"

There are several other terms that should be harmonized, but I am saving them for later because they do not cause the same degree of confusion as the ones above.

The first commit of the series simply corrects translation errors, and the remaining commits deal with the harmonization itself.

### CODE REVIEW

**Comment by alexhenrie** [comment]
Crud, I meant to send this merge request to [ChrisADR](https://github.com/ChrisADR/git-po), not git-l10n directly, sorry. Please ignore.

**Comment by alexhenrie** [comment]
I'm reopening this pull request here because the Spanish translation maintainer, @ChrisADR, has not responded.

**Comment by jiangxin** [comment]
Hi @alexhenrie,

The l10n workflow has changed since this release cycle. See the discussion in this thread:

+ https://lore.kernel.org/git/20220503132354.9567-1-worldhello.net@gmail.com/

If it is hard to fix the above errors, I can help.

**Comment by alexhenrie** [comment]
Hi Jiang, thanks for that information. I have updated the PO file format and squashed my changes into a single commit for your convenience. There are still a couple of warnings because I am only trying to fix problems in existing translations; for the moment I'm not trying to translate all of the new strings.

**Comment by alexhenrie** [comment]
Thank you!

**Pull request merged**
