### PR TITLE
l10n: Tamil Translation - ta.po file Created

### PR DESCRIPTION
**Pull request by TamilNeram**
This is a Tamil Translation / localization file with just few entries. I will be adding the translations incrementally based on checks and reviews.

### CODE REVIEW

**Comment by jiangxin** [comment]
> This is a Tamil Translation / localization file with just few entries. I will be adding the translations incrementally based on checks and reviews.

Thank you for providing a new language support for Git. You will find some l10n conventions in [po/README.md](https://github.com/git-l10n/git-po/blob/master/po/README.md#conventions), and there is a helper program that will check your contributions based on these conventions.

You can [mark your pull request as DRAFT](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request) before it's ready for merge. And you should complete the core set of l10n messages, see the descriptions about the "po/git-core.pot" file in section [Dynamically generated POT files](https://github.com/git-l10n/git-po/blob/master/po/README.md#dynamically-generated-pot-files).

**Comment by jiangxin** [comment]
Cannot merge commits you provided as below:

```
0af596cde8 Merge branch 'git-l10n:master' into master
7834f6f847 மேபை
241520ae4a --rebase-merges
4f5497d2df --init
9b59102c58 %%(trailers:key=<
d00a942232  --verify-signatures
77357e72b5 Merge branch 'master' of https://github.com/Nizhal/git-po
cc4cd8a7ff split தவிர்
572ec4ae34 splitIndex.maxPercentChange fixed
83a22a426a fixed few more formatting issues
37cb7f9a2a #: [a-z/.:0-9\- ]+
d5efc40ccf fixed few Errors
e7420dafc1 fixed all local errors
614ee9e481 fanout
716d8f9fb4 PRIuMAX fixed
87c8c0169f fixed few more messages
f3405d7485 26771
4fc50b3ecb %shint fixed
fa2a49455e fixed %c formatting
b144b3b3f2 fixed %.*.s - formatting
bfb31ba91e updated
bd7dc15e5e \n
26df8032f8 28702 வரிகள் மிதம்
42d0145b51 update 3 with all messages
3bbf7bcf51 update2
ff75f4ae67 update1
3d08c2dd57 தமி (Tamil) - ta.po file Created
```

You should check and learn to write commit logs from other l10n contributors:

```
git log -- po/de.po
git log -- po/fr.po 
```

**Comment by TamilNeram** [comment]
Hi @jiangxin, 
                     I am unable to find the right make tools for windows operating system.  Please recommend the right one to run the validation locally.

**Comment by jiangxin** [comment]
> Hi @jiangxin, I am unable to find the right make tools for windows operating system. Please recommend the right one to run the validation locally.

The helper program for l10n is written in golang. I suppose it could be compiled on Windows, at least on Windows Subsystem for Linux (WSL).

You can try to install using:

    go install github.com/git-l10n/git-po-helper@latest

Or you can clone source code locally:

    git clone https://github.com/git-l10n/git-po-helper.git

Compile and install:

    cd git-po-helper
    make

**Pull request closed without merging**
