### PR TITLE
l10n: bg.po: Updated Bulgarian translation (5489t)

### PR DESCRIPTION
**Pull request by alshopov**

### CODE REVIEW

**Comment by jiangxin** [comment]
Additional 4 new l10n messages were found in upstream, so I manually triggered the github actaion. You can rebase, rebuilt and translate your po file.

**Comment by alshopov** [comment]
> You can rebase, rebuilt and translate
Done.

**Comment by jiangxin** [comment]
Git 2.40.0-rc1 was released with 1 additional l10n message,  you can see the output from the CI pipeline which I triggered manually. Please rebase, update and translate the po file.

**Comment by alshopov** [comment]
> Please rebase...

Done

**Comment by alshopov** [comment]
Are you waiting for Git 2.40-rc2 to merge this?

**Comment by jiangxin** [comment]
> Are you waiting for Git 2.40-rc2 to merge this?

Right. To reduce the number of merge commits, I'd like to see if there are further updates for l10n in Git v2.40-rc2.

**Pull request merged**
