### PR TITLE
Fix a typo in the French translation

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by jnavila** [comment]
Please open a pull request to my repo jnavila/git and follow the guidelines for patches in Documentation/SubmittingPatches:

*  add a prefix "l10n: fr.po" to the title of the patch
* add a "Signed-off-by:" line by committing with option "-s"

**Comment by jiangxin** [comment]
OK, I will close this PR.

**Comment by nox** [comment]
Are you carrying the patch, or do I still have to do submitting on @jnavila's repos?

**Comment by jnavila** [comment]
@jiangxin surely would not propose a patch for the french translation :laughing:

**Comment by nox** [comment]
I'm willing to do another PR on your fork, but I won't bother setting up commit signing. The guidelines says "Do not PGP sign your patch, at least for now." and the first time I submitted a patch to Git I didn't need it.

**Pull request closed without merging**
