### PR TITLE
Update Vietnamese team contact

### PR DESCRIPTION
**Pull request by Nekosha**

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @vnwildman, can you help me approve this pull request from @Nekosha ?

**Comment by jiangxin** [comment]
> Errors and warnings found by [git-po-helper](https://github.com/git-l10n/git-po-helper#readme) in workflow [#629](/git-l10n/git-po/actions/runs/8549445042):
> 
> ```
> ------------------------------------------------------------------------------
> ERROR commit f8a475b: subject ("Update Vietnamese ...") does not have prefix "l10n:" 
> ------------------------------------------------------------------------------
> ERROR commit f8a475b: line #3 ("The previous ...") is too long: 112 > 72 
> INFO checking commits: 0 passed, 1 failed.        
> ------------------------------------------------------------------------------
> INFO downloading pot file from https://github.com/git-l10n/pot-changes/raw/pot/master/po/git.pot 
> 
> ERROR: fail to execute "git-po-helper check-commits"
> ```

@Nekosha , we have a CI system (based on GitHub Actions) to find issues on l10n contributions. Please fix the above issues.

**Comment by jiangxin** [comment]
In the trailer you leave your signature with an email address unable to reach:

    Signed-off-by: Nekosha <79341606+Nekosha@users.noreply.github.com>

How about using your email address or signature in TEAMS file?

    Vũ Tiến Hưng <newcomerminecraft@gmail.com>

**Comment by vnwildman** [comment]
> Hi @vnwildman, can you help me approve this pull request from @Nekosha ?

Hi, @jiangxin, yes, please approve @Nekosha as coordinator of Vietnamese Git translate team.
@Nekosha should use real full name to sign any commit.
Well come @Nekosha joint this team!

**Comment by Nekosha** [comment]
Thanks, I've fixed the commit message.

**Comment by Nekosha** [comment]
Fixed the author info.

**Pull request merged**
