### PR TITLE
l10n: zh_CN: v2.37.0 round 1

### PR DESCRIPTION
**Pull request by fangyi-zhou**
Reviewed-by: Jiang Xin <worldhello.net@gmail.com>
Signed-off-by: Fangyi Zhou <me@fangyi.io>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
I created a patch to upstream for `autoSetupMerge` https://github.com/git/git/pull/1276

**Comment by jiangxin** [comment]
Please rebase to the latest commit of the master branch, and update your "po/zh_CN.po" again using:

```
make po-update PO_FILE=po/zh_CN.po
```

**Comment by fangyi-zhou** [comment]
v1-v2 diff: https://gist.github.com/fangyi-zhou/77d57fd31d3b3ac339b7a76293294ce8
v2-v3 diff: https://gist.github.com/fangyi-zhou/5d6c79c1eee1220c45f9ee9e550940a6

**Comment by jiangxin** [comment]
> v1-v2 diff: https://gist.github.com/fangyi-zhou/77d57fd31d3b3ac339b7a76293294ce8
> v2-v3 diff: https://gist.github.com/fangyi-zhou/5d6c79c1eee1220c45f9ee9e550940a6

for v3:

```
-msgstr  "（已删除）尝试重建合并提交而非忽略它们"
+msgstr  "（已删除）曾是：尝试重建合并提交而非忽略它们"

-        "或者降级至 v2.33 或更早来完成此次变基。"
+        "或者降级至 v2.33 或更早的版本来完成此次变基。"
```

**Comment by jiangxin** [comment]
Will merge after Junio releases rc2.

1. If there are new l10n strings that need to be translated, I will trigger the CI for this PR again, and you will be notified that further updates should be made.
2. If there are no update for release rc2, this PR will be merged.

**Pull request merged**
