### PR TITLE
l10n: pt_PT: cleaning duplicate translations (#2)

### PR DESCRIPTION
**Pull request by alexandre1985**
* cleaning duplicate incorrect translations part 2
 * update translation table
 * unfuzzy some entries
 * random line translations

Signed-off-by: Daniel Santos <hello@brighterdan.com>

### CODE REVIEW

**Comment by jiangxin** [comment]
Please squash these commits and fix typos:

```
INFO [po/pt_PT.po@99eb02c]      4078 translated messages, 1152 untranslated messages. 
WARNING [po/pt_PT.po@99eb02c]   mismatch variable names: %%(algn), %%(align) 
WARNING [po/pt_PT.po@99eb02c]   >> msgid: positive width expected with the %%(align) atom 
WARNING [po/pt_PT.po@99eb02c]   >> msgstr: largura positiva esperada com o átomo %%(algn) 
WARNING                                              
INFO [po/pt_PT.po@96a1513]      4064 translated messages, 1166 untranslated messages. 
WARNING [po/pt_PT.po@96a1513]   mismatch variable names: %%(algn), %%(align) 
WARNING [po/pt_PT.po@96a1513]   >> msgid: positive width expected with the %%(align) atom 
WARNING [po/pt_PT.po@96a1513]   >> msgstr: largura positiva esperada com o átomo %%(algn) 
WARNING                                              
ERROR commit 96a1513: commit log message is too long (81 > 72) 
INFO [po/pt_PT.po@c852c5f]      3025 translated messages, 1033 fuzzy translations, 1172 untranslated messages. 
WARNING [po/pt_PT.po@c852c5f]   mismatch variable names: %%(algn), %%(align) 
WARNING [po/pt_PT.po@c852c5f]   >> msgid: positive width expected with the %%(align) atom 
WARNING [po/pt_PT.po@c852c5f]   >> msgstr: largura positiva esperada com o átomo %%(algn) 
WARNING                                              
INFO checking commits: 3 passed, 1 failed.        

ERROR: fail to execute "git-po-helper check-commits"
```

**Comment by alexandre1985** [comment]
@jiangxin I am completely lost and don't know what to do.
I have tried squashing old commits and fixed the `%%(align)` typo

**Comment by jiangxin** [comment]
> INFO successfully fetched 1 missing blob(s) in a batch from partial clone 
> INFO [po/pt_PT.po@42b297f]	4078 translated messages, 1152 untranslated messages. 
> ERROR commit 42b297f: bad committer date: date is in the future, 5m32s from now 

Git uses commit date to calculate commit-graph, if the commit date is far away from now, git will make calibrations on all commits follows.  "5m32s" is not a big deviation, I just wonder how this deviation happened.

> WARNING commit 42b297f: author (Daniel Santos <hello@brighterdan.com>) and committer (Daniel Santos <daniel@brilhante.top>) are different 
> INFO checking commits: 0 passed, 1 failed.

You can rewrite your commit to make the same author name and committer name:
```
    git commit --amend --reset-author
```

**Comment by jiangxin** [comment]
If you believe it OK to have different author name and committer name, tell me, I can merge this PR.

This check is only used to prevent malicious forgery of signatures.

**Comment by jiangxin** [comment]
> @jiangxin I am completely lost and don't know what to do. I have tried squashing old commits and fixed the `%%(align)` typo

Squash all trivial commits is OK. If you want to keep the history commits, you can make an interactive rebase, and fix typo issues for each commit one by one.

**Pull request merged**
