### PR TITLE
l10n: sv.po: Update Swedish translation

### PR DESCRIPTION
**Pull request by nafmo**

### CODE REVIEW

**Comment by nafmo** [comment]
> ERROR commit c1a1a78: cannot find "Signed-off-by:" signature 

Something seems to be wrong with the tool?

**Comment by jiangxin** [comment]
> wrong with the tool?

s/Signed-Off-by:/Signed-off-by:/

**Comment by jiangxin** [comment]
Hi  @nafmo ,

To fix the issue, created a new pull request, see: #790.

**Comment by nafmo** [comment]
>> wrong with the tool?
>
> s/Signed-Off-by:/Signed-off-by:/

Oh. Didn't notice the difference... I never use such lines anywhere 
else, and added a hook to make sure I didn't forget. Will fix for next 
time.

-- 
\\// Peter - http://www.softwolves.pp.se/

**Comment by nafmo** [comment]
> s/Signed-Off-by:/Signed-off-by:/

I'm apparently not very consistent in casing:

https://github.com/nafmo/git-l10n-sv/commit/8198993c817b6c3b42f91c7345469c113c6eeabc

:-)

-- 
\\// Peter - http://www.softwolves.pp.se/

**Pull request closed without merging**
