### PR TITLE
Fix typo in french translation

### PR DESCRIPTION
**Pull request by claudusd**
Hi,

A little fix on a typo in the french translation.

### CODE REVIEW

**Comment by jiangxin** [comment]
According to [the TEAMS file](https://github.com/git/git/blob/master/po/TEAMS), you should send pull request to [jnavila/git](https://github.com/jnavila/git) project and reviewed by @jnavila.

**Comment by jiangxin** [comment]
According to [the TEAMS file](https://github.com/git/git/blob/master/po/TEAMS), you should send pull request to [jnavila/git](https://github.com/jnavila/git) project and reviewed by @jnavila.

**Comment by jnavila** [comment]
Je ne peux pas picorer ton commit, car il manque la ligne Signed-off-by:

Ce que je te propose : je l'intègre dans mes prochaines mises à jour, en ajoutant ta signature.

Merci

**Comment by claudusd** [comment]
Ok !

Merci.

--
Claude Dioudonnat
 
 
Le Mar 16 juin 2015, à 17:20, Jean-Noël Avila a écrit :
> Je ne peux pas picorer ton commit, car il manque la ligne Signed-off-by:


> Ce que je te propose : je l'intègre dans mes prochaines mises à jour, en ajoutant ta signature.


> Merci


> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/git-l10n/git-po/pull/127#issuecomment-112468623

**Pull request closed without merging**
