### PR TITLE
l10n: Update Catalan translation

### PR DESCRIPTION
**Pull request by jordimas**
Signed-off-by: Jordi Mas <jmas@softcatala.org>

### CODE REVIEW

**Comment by jiangxin** [comment]
Will be held until the open of l10n window of git 2.35 opens on January 10.

**Comment by jordimas** [comment]
Friendly reminder: it will be great if we can merge this. Thanks

**Comment by jiangxin** [comment]
I found there are many trivial commits with the same log message "Update Catalan translation" in your branch. Would you like to squash all these commits and update this pull request? or you can close this pull request and create another one.

```
$ git log --oneline ..l10n/ca/softcatala/catalan
1256a3b0db (l10n/ca/softcatala/catalan) Update Catalan translation
9890a665ae Update Catalan translation
2ba8ae3bf8 Update Catalan translation
4a75630d58 Update Catalan translation
d16512a42a Update Catalan translation
019cbb191e Update Catalan translation
bda98a6f9c Update Catalan translation
cdec4c1336 Update Catalan translation
aa963f218e Update Catalan translation
b5cb264128 Update Catalan translation
e6ebb749ea Update Catalan translation
52f8b68a48 Update Catalan translation
bd91e4a9e2 Update Catalan translation
13274563f0 Update Catalan translation
752bf869d0 Update Catalan translation
98d3176510 Update Catalan translation
5f4f42007d Update Catalan translation
c2132a902d Update Catalan translation
198c2cff66 Update Catalan translation
1c3ec05720 Update Catalan translation
d81ef8fe03 Update Catalan translation
f39cb83db4 Update Catalan translation
7929ee81df Update Catalan translation
4b154618c7 Update Catalan translation
dc61a25c89 Update Catalan translation
c6e02688d5 Update Catalan translation
bb54f01fed Update Catalan translation
61bddadae6 Update Catalan translation
1edc10ac13 Update Catalan translation
752da81bee Update Catalan translation
88bc66b3f8 Update Catalan translation
692aa89eaf Update Catalan translation
0ec6c35343 Update Catalan translation
0ee6206f75 Update Catalan translation
518405774f Update Catalan translation
781c9e9a7c Update Catalan translation
e3288fa789 Merge branch 'MartiRubio-catalan-marti-rubio' into catalan
fd84990079 Traducció augmentada
5eaa2fd080 (l10n/ca/softcatala/master, refs/pull/598/head) l10n: Update Catalan translation
```

**Comment by jordimas** [comment]
This is still work in progress that I still need to proofread. I will do a second PR in the near future. Thanks

**Comment by jordimas** [comment]
I will open a new PR.

**Pull request closed without merging**
