### PR TITLE
l10n: zh_TW: v2.35.0 round 2 (0 untranslated) 

### PR DESCRIPTION
**Pull request by pan93412**
Signed-off-by: Yi-Jyun Pan <pan93412@gmail.com>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
Is this ready to merge with a fuzzy translation in it?

**Comment by pan93412** [comment]
> Is this ready to merge with a fuzzy translation in it?

I think we can merge it after completing round 2's part.

**Comment by s8321414** [comment]
Looks good to me.

**Comment by jiangxin** [comment]
> > Is this ready to merge with a fuzzy translation in it?
> 
> I think we can merge it after completing round 2's part.

Please note that the l10n window will close this Sunday. You can update your change based on l10n rount 2 now.

**Comment by pan93412** [comment]
r? @jiangxin 
Thanks!

**Pull request merged**
