### PR TITLE
l10n: bg.po: Updated Bulgarian translation (5579t)

### PR DESCRIPTION
**Pull request by alshopov**
Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by alshopov** [comment]
Fixes coming...

**Comment by alshopov** [comment]
TBH I am not sure what is the exact problem with that message, suggestions welcome

**Comment by jiangxin** [comment]
> TBH I am not sure what is the exact problem with that message, suggestions welcome

The first word for `--dirstat` cannot be translated. E.g.:

    git diff <commit1> <commit2> --dirstat=files
    
According to the following code

 * https://github.com/git/git/blob/v2.44.0-rc0/diff.c#L5601-L5604

calling `git diff --dirstat-by-file[=<param1,param2>...]` is the same as calling:

    git diff --dirstat=files,param1,param2...

From code of the function diff_opt_dirstat() as below:

 * https://github.com/git/git/blob/v2.44.0-rc0/diff.c#L5265-L5266

We can see the first parameter for long option --dirstat-by-file is "files"
which cannot be translated. But other parameters such as param1 and param2
should be given in "<place-holder>" format.

You can make change of the source code of Git, and send patch to upstream:

```
--- a/diff.c
+++ b/diff.c
@@ -5598,7 +5598,7 @@ struct option *add_diff_options(const struct option *opts,
                               PARSE_OPT_NONEG | PARSE_OPT_NOARG,
                               diff_opt_dirstat),
                OPT_CALLBACK_F(0, "dirstat-by-file", options, N_("<param1,param2>..."),
-                              N_("synonym for --dirstat=files,param1,param2..."),
+                              N_("synonym for --dirstat=files,<param1>,<param2>..."),
                               PARSE_OPT_NONEG | PARSE_OPT_OPTARG,
                               diff_opt_dirstat),
                OPT_BIT_F(0, "check", &options->output_format,
```

**Comment by jiangxin** [comment]
Even when you updated bg.po as below,

    msgstr: псевдоним на „--dirstat=files,ПАРАМЕТЪР_1,ПАРАМЕТЪР_2,…“

will report the same error message:

```
------------------------------------------------------------------------------
ERROR [po/bg.po]        mismatched patterns: --dirstat=, --dirstat=files 
ERROR [po/bg.po]        >> msgid: synonym for --dirstat=files,param1,param2... 
ERROR [po/bg.po]        >> msgstr: псевдоним на „--dirstat=files,ПАРАМЕТЪР_1,ПАРАМЕТЪР_2,…“ 
ERROR [po/bg.po]                                   
------------------------------------------------------------------------------
```

This is because the smudge entries defined below:

 * https://github.com/git-l10n/git-po-helper/blob/v0.7.3/dict/smudge-bg.go#L124-L151

I will try to fix the smudge table for bg in git-po-helper.

**Comment by jiangxin** [comment]
A new translatable message has been introduced in Git upstream, please update your translations.

**Comment by jiangxin** [comment]
Commit ["diff: mark param1 and param2 as placeholders"](https://lore.kernel.org/git/3a82f72f33663f162aa41cb20c0fb3b6786971c9.1707900029.git.worldhello.net@gmail.com/) has been merged, and two translatable messages have been changed. Let's start the 3rd (and perhaps final) round of l10n.

**Pull request merged**
