### PR TITLE
l10n: Updated Vietnamese translation for v2.21 rd2

### PR DESCRIPTION
**Pull request by vnwildman**
Signed-off-by: Tran Ngoc Quan <vnwildman@gmail.com>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use submitGit to conveniently send your Pull
Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
Find errors when validating your  `po/vi.po` using gettext 0.14.4.

    vi.po     : 4363 translated messages.
    po/vi.po:22135:4: parse error
    po/vi.po:22135: missing `msgstr' section
    /opt/gettext/0.14.4/bin/msgfmt: found 2 fatal errors

See discussions in git list: https://public-inbox.org/git/CANYiYbF_6U6x7fCV6LNt_c8yc9mF0PhwdqXdQNHB9eP5onDUKw@mail.gmail.com/T/#m1abc2bd40c52cca0bd4f2bc575a18dc2b72396c1

**Comment by vnwildman** [comment]
I tested vi and fr on Debian and it Ok.

$ uname -a
Linux vnwildman 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
$ LANG=C msgfmt -V
msgfmt (GNU gettext-tools) 0.19.8.1
$ LANG=C msgfmt -cv vi.po
4363 translated messages.

I seem your/builder gettext version is low. If we have to support this version, so delete/edit those strings manualy.

**Comment by jiangxin** [comment]
> I seem your/builder gettext version is low. If we have to support this version, so delete/edit those strings manualy.

No doubt I use the latest version of gettext, but other guys may find it is difficult to build git under NetBSD, because gettext version is old on these platform, and cannot be upgraded easyly. See the link I provided in previous post.

Please remove one of the duplicated msgid in comments.

**Comment by jiangxin** [comment]
See https://public-inbox.org/git/CANYiYbF_6U6x7fCV6LNt_c8yc9mF0PhwdqXdQNHB9eP5onDUKw@mail.gmail.com/T/#m1abc2bd40c52cca0bd4f2bc575a18dc2b72396c1 and pull request #358

**Comment by vnwildman** [comment]
I don't recommend for delete all deleted message strings, because they may be use in future. I suggest NetBSD user should delete those strings by using `sed' command (or others) before he/she can build it.

**Comment by jiangxin** [comment]
cherry-picked your commit, and removed one line which had duplicate msgid.

**Pull request closed without merging**
