### PR TITLE
l10n: sv.po: Update Swedish translation (5367t0f0u)

### PR DESCRIPTION
**Pull request by nafmo**
Run msgmerge with --no-location to drop file locations to decrease the
size of future patches.

Signed-off-by: Peter Krefting <peter@softwolves.pp.se>

Thanks for taking the time to contribute to Git! Please be advised that the
Git community does not use github.com for their contributions. Instead, we use
a mailing list (git@vger.kernel.org) for code submissions, code reviews, and
bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/)
to conveniently send your Pull Requests commits to our mailing list.

Please read the "guidelines for contributing" linked above!

### CODE REVIEW

**Comment by jiangxin** [comment]
Hi @nafmo, 

The above errors from the CI pipeline indicate that you should remove the obsolete entry in the comments at the end of the po/sv.po file, like:

```
#, c-format
#~ msgid ""
#~ "CRLF will be replaced by LF in %s.\n"
#~ "The file will have its original line endings in your working directory"
#~ msgstr ""
#~ "CRLF kommer att ersättas av LF i %s.\n"
#~ "Filen kommer att ha sina ursprungliga radbrytningar i din arbetskatalog"

#, c-format
#~ msgid ""
#~ "LF will be replaced by CRLF in %s.\n"
#~ "The file will have its original line endings in your working directory"
#~ msgstr ""
#~ "LF kommer att ersättas av CRLF i %s.\n"
#~ "Filen kommer att ha sina ursprungliga radbrytningar i din arbetskatalog"

... ...
```

**Comment by nafmo** [comment]
Hi!

> The above errors from the CI pipeline indicate that you should remove the obsolete entry in the comments at the end of the po/sv.po file, like:

I have been keeping them as a translation memory. From time to time, a 
new message pops up that looks like one that has been previously 
removed, and having a fallback can be useful.

-- 
\\// Peter - http://www.softwolves.pp.se/

**Comment by jiangxin** [comment]
> I have been keeping them as a translation memory. From time to time, a new message pops up that looks like one that has been previously removed, and having a fallback can be useful.

It's a bit uneconomical to keep all deleted entries this way, as if we don't delete any obsolete C functions in the C source files and comment them out.

We can create tools to let version control system to help us. For example: call msgcat on all historical versions to create a big po file for reference.

**Comment by jiangxin** [comment]
Hi, you removed obsolete translations in commit ca6df98, but still leave them in commit 208fcb7, and still have an impact on git repository. Please squash them into one commit.

**Comment by jiangxin** [comment]
Before send pull request Junio tonight, I will help to squash the two commits for you. And will close this pull request.

**Pull request closed without merging**
