### PR TITLE
l10n: zh_TW: add translation for v2.24.0

### PR DESCRIPTION
**Pull request by pan93412**

### CODE REVIEW

**Comment by jiangxin** [comment]
Thank you for contributing. I see the translation of traditional Chinese is almost complete. The are still lots of time (2 months) before the next l10n merge window, you can use this time to polish your work.  I will merge as soon as you feel perfect. Please:

1. Update the file `po/TEAMS`, add the zh_TW team in it.
2. Squash the fixup commits into one complete initial commit with proper signatures (Signed-off-by, Reviewed-by, ..., etc)
3. Follow the l10n contribution guidelines. You can learn from other l10n contributors from commits or from history pull requests. E.g. 1) use "l10n:" or "l10n: zh_TW:" as prefix of your commit; 2) add "Signed-off-by" lines; 3) pass the check of `po-helper.sh` script (https://github.com/git-l10n/git-po/blob/po-helper/utils/po-helper.sh).

**Comment by jiangxin** [comment]
Besides, you can set the appropriate author name for your commit, it's no need to be your login name (pan93412).

    git config --global user.name "<Your-Real-Name>"
    git commit --amend --reset-author

**Comment by pan93412** [comment]
Thanks! :)

**Comment by pan93412** [comment]
@jiangxin Is it right? I've followed all the instruction you gave, but I am not sure if I do right.

**Comment by jiangxin** [comment]
> Thanks! :)

1. Please fix format problems in `po/TEAMS`. Using tabs instead of spaces, and do not add empty line at the end.

        --- a/po/TEAMS
        +++ b/po/TEAMS
        @@ -67,3 +67,9 @@ Leader:               Jiang Xin <worldhello.net AT gmail.com>
         Members:       Ray Chen <oldsharp AT gmail.com>
                        依云 <lilydjwg AT gmail.com>
                        Fangyi Zhou <me AT fangyi.io>
        +
        +Language:    zh_TW (Traditional Chinese)
        +Respository: https://github.com/l10n-tw/git-po
        +Leader:      Yi-Jyun Pan <pan93412 AT gmail.com>
        +Members:     Franklin Weng <franklin@goodhorse.id
        +

2. Fix s-o-b lines in your commit, do not align user name with spaces, please follow the convention. See commit log history and check how other contributors write commit log.

**Comment by pan93412** [comment]
@jiangxin Done, please review this. :)

**Comment by jiangxin** [comment]
> @jiangxin Done, please review this. :)

Still some issues in your commit log:

1. If you look at the git commit log, you'll find that most people use "Reviewed-by: " for acknowledgement, even if someone mistakenly use "Reviewed-By: ".  Please use "Reviewed-by: ", instead of "Reviewed-By: ".

2. You added a commit reference in your commit log, please follow the convention. See the "commit-reference" section in "Documentation/SubmittingPatches":

        $ git show -s --date=short --pretty='format:%h ("%s", %ad)' a5cd71c
          a5cd71ca4a ("l10n: zh_CN: for git v2.24.0 l10n round 1~2", 2019-10-29)

3. Ask the reviewer (fweng322) for his prefered user name.

So your commit log should write like this:

    l10n: zh_TW: add translation for v2.24.0

    Based on commit a5cd71ca4a ("l10n: zh_CN: for git v2.24.0 l10n round 1~2", 2019-10-29).
    
    Signed-off-by: Yi-Jyun Pan <pan93412@gmail.com>
    Reviewed-by: "Real Name" <franklin@goodhorse.idv.tw>

**Comment by pan93412** [comment]
@jiangxin Ok, can you check it again? Thanks! ;)

**Comment by pan93412** [comment]
LGTM currently, and I would submit a new patch if I found any wrong.

**Comment by jiangxin** [comment]
Lines of the commit log should not longer than 72 characters. I tweaked the commit log, and merged. Please rebase to the master branch.

**Pull request closed without merging**
