### PR TITLE
l10n: Update Catalan translation

### PR DESCRIPTION
**Pull request by jordimas**
Signed-off-by: Jordi Mas <jmas@softcatala.org>

### CODE REVIEW

**Comment by jiangxin** [comment]
Next l10n update window will open on May 10th or later, and will merge at that time.  @jordimas , you can squash more update commits into one.

**Comment by jordimas** [comment]
Can we merge this please? Thanks

**Comment by jiangxin** [comment]
I was wating for further updates. Merged

**Comment by jordimas** [comment]
Thanks!

**Pull request merged**
